-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity KeccakWidth1600_Spon_5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    instance_state_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    instance_state_ce0 : OUT STD_LOGIC;
    instance_state_we0 : OUT STD_LOGIC;
    instance_state_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    instance_state_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    data_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    data_0_ce0 : OUT STD_LOGIC;
    data_0_we0 : OUT STD_LOGIC;
    data_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    data_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    data_1_ce0 : OUT STD_LOGIC;
    data_1_we0 : OUT STD_LOGIC;
    data_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    data_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    data_2_ce0 : OUT STD_LOGIC;
    data_2_we0 : OUT STD_LOGIC;
    data_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    data_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    data_3_ce0 : OUT STD_LOGIC;
    data_3_we0 : OUT STD_LOGIC;
    data_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    dataByteLen : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of KeccakWidth1600_Spon_5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000010000000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000100000000";
    constant ap_ST_fsm_pp1_stage1 : STD_LOGIC_VECTOR (20 downto 0) := "000000000001000000000";
    constant ap_ST_fsm_pp1_stage2 : STD_LOGIC_VECTOR (20 downto 0) := "000000000010000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (20 downto 0) := "000000000100000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (20 downto 0) := "000000001000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (20 downto 0) := "000000010000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (20 downto 0) := "000000100000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (20 downto 0) := "000001000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (20 downto 0) := "000010000000000000000";
    constant ap_ST_fsm_pp2_stage0 : STD_LOGIC_VECTOR (20 downto 0) := "000100000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (20 downto 0) := "001000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (20 downto 0) := "010000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (20 downto 0) := "100000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv33_0 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_A8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101000";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv8_C8 : STD_LOGIC_VECTOR (7 downto 0) := "11001000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal KeccakRhoOffsets_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal KeccakRhoOffsets_ce0 : STD_LOGIC;
    signal KeccakRhoOffsets_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal KeccakRoundConstants_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal KeccakRoundConstants_ce0 : STD_LOGIC;
    signal KeccakRoundConstants_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten_reg_275 : STD_LOGIC_VECTOR (4 downto 0);
    signal x_0_i_reg_286 : STD_LOGIC_VECTOR (2 downto 0);
    signal y_0_i_reg_298 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten7_reg_309 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_0_i2_reg_320 : STD_LOGIC_VECTOR (4 downto 0);
    signal j_0_i5_reg_331 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln304_fu_393_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln304_reg_850 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln322_fu_397_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln322_reg_855 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln305_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln305_reg_863 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln304_fu_401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln269_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_19_fu_418_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_19_reg_871 : STD_LOGIC_VECTOR (4 downto 0);
    signal stateAsWords_addr_1_reg_876 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln_fu_429_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln_reg_881 : STD_LOGIC_VECTOR (7 downto 0);
    signal j_fu_443_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_reg_889 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln271_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln293_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal i_21_fu_502_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_21_reg_903 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln352_fu_508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln352_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_block_state9_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state12_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal add_ln352_fu_514_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln352_reg_912 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal x_fu_520_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_reg_917 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln352_1_fu_526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln352_1_reg_922 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln353_1_fu_532_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln353_1_reg_927 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln353_2_fu_540_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln353_2_reg_935 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_pp1_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage1 : signal is "none";
    signal ap_block_state10_pp1_stage1_iter0 : BOOLEAN;
    signal ap_block_pp1_stage1_11001 : BOOLEAN;
    signal icmp_ln353_fu_621_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln353_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal stateAsWords_addr_3_reg_950 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln353_fu_663_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln353_reg_956 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_pp1_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage2 : signal is "none";
    signal ap_block_state11_pp1_stage2_iter0 : BOOLEAN;
    signal ap_block_pp1_stage2_11001 : BOOLEAN;
    signal y_fu_670_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal y_reg_961 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal icmp_ln280_fu_687_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln280_reg_971 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp2_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp2_stage0 : signal is "none";
    signal ap_block_state19_pp2_stage0_iter0 : BOOLEAN;
    signal ap_block_state20_pp2_stage0_iter1 : BOOLEAN;
    signal ap_block_state21_pp2_stage0_iter2 : BOOLEAN;
    signal ap_block_pp2_stage0_11001 : BOOLEAN;
    signal icmp_ln280_reg_971_pp2_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln280_fu_693_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp2_iter0 : STD_LOGIC := '0';
    signal select_ln280_fu_711_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln280_reg_980 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln280_reg_980_pp2_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln280_2_fu_719_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln280_2_reg_985 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln280_2_reg_985_pp2_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln282_fu_732_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln282_reg_996 : STD_LOGIC_VECTOR (2 downto 0);
    signal j_9_fu_736_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln282_2_fu_759_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln282_2_reg_1006 : STD_LOGIC_VECTOR (7 downto 0);
    signal partialBlock_fu_788_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal partialBlock_reg_1011 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal partialBlock_21_fu_810_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal partialBlock_21_reg_1017 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal i_fu_826_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal i_reg_1022 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln332_fu_832_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln332_reg_1027 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln331_fu_838_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln331_reg_1032 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_theta_fu_379_ap_ready : STD_LOGIC;
    signal grp_theta_fu_379_ap_done : STD_LOGIC;
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state9 : STD_LOGIC;
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal ap_block_pp1_stage2_subdone : BOOLEAN;
    signal ap_block_pp2_stage0_subdone : BOOLEAN;
    signal ap_condition_pp2_exit_iter0_state19 : STD_LOGIC;
    signal ap_enable_reg_pp2_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp2_iter2 : STD_LOGIC := '0';
    signal stateAsWords_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal stateAsWords_ce0 : STD_LOGIC;
    signal stateAsWords_we0 : STD_LOGIC;
    signal stateAsWords_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal stateAsWords_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal stateAsWords_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal stateAsWords_ce1 : STD_LOGIC;
    signal stateAsWords_we1 : STD_LOGIC;
    signal stateAsWords_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal stateAsWords_q1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_KeccakP1600_ExtractB_fu_355_ap_start : STD_LOGIC;
    signal grp_KeccakP1600_ExtractB_fu_355_ap_done : STD_LOGIC;
    signal grp_KeccakP1600_ExtractB_fu_355_ap_idle : STD_LOGIC;
    signal grp_KeccakP1600_ExtractB_fu_355_ap_ready : STD_LOGIC;
    signal grp_KeccakP1600_ExtractB_fu_355_state_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_KeccakP1600_ExtractB_fu_355_state_ce0 : STD_LOGIC;
    signal grp_KeccakP1600_ExtractB_fu_355_data_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_KeccakP1600_ExtractB_fu_355_data_0_ce0 : STD_LOGIC;
    signal grp_KeccakP1600_ExtractB_fu_355_data_0_we0 : STD_LOGIC;
    signal grp_KeccakP1600_ExtractB_fu_355_data_0_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_KeccakP1600_ExtractB_fu_355_data_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_KeccakP1600_ExtractB_fu_355_data_1_ce0 : STD_LOGIC;
    signal grp_KeccakP1600_ExtractB_fu_355_data_1_we0 : STD_LOGIC;
    signal grp_KeccakP1600_ExtractB_fu_355_data_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_KeccakP1600_ExtractB_fu_355_data_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_KeccakP1600_ExtractB_fu_355_data_2_ce0 : STD_LOGIC;
    signal grp_KeccakP1600_ExtractB_fu_355_data_2_we0 : STD_LOGIC;
    signal grp_KeccakP1600_ExtractB_fu_355_data_2_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_KeccakP1600_ExtractB_fu_355_data_3_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_KeccakP1600_ExtractB_fu_355_data_3_ce0 : STD_LOGIC;
    signal grp_KeccakP1600_ExtractB_fu_355_data_3_we0 : STD_LOGIC;
    signal grp_KeccakP1600_ExtractB_fu_355_data_3_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_pi_fu_374_ap_start : STD_LOGIC;
    signal grp_pi_fu_374_ap_done : STD_LOGIC;
    signal grp_pi_fu_374_ap_idle : STD_LOGIC;
    signal grp_pi_fu_374_ap_ready : STD_LOGIC;
    signal grp_pi_fu_374_A_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_pi_fu_374_A_ce0 : STD_LOGIC;
    signal grp_pi_fu_374_A_we0 : STD_LOGIC;
    signal grp_pi_fu_374_A_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_pi_fu_374_A_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_pi_fu_374_A_ce1 : STD_LOGIC;
    signal grp_pi_fu_374_A_we1 : STD_LOGIC;
    signal grp_pi_fu_374_A_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_theta_fu_379_ap_start : STD_LOGIC;
    signal grp_theta_fu_379_ap_idle : STD_LOGIC;
    signal grp_theta_fu_379_A_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_theta_fu_379_A_ce0 : STD_LOGIC;
    signal grp_theta_fu_379_A_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_theta_fu_379_A_ce1 : STD_LOGIC;
    signal grp_theta_fu_379_A_we1 : STD_LOGIC;
    signal grp_theta_fu_379_A_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_chi_fu_384_ap_start : STD_LOGIC;
    signal grp_chi_fu_384_ap_done : STD_LOGIC;
    signal grp_chi_fu_384_ap_idle : STD_LOGIC;
    signal grp_chi_fu_384_ap_ready : STD_LOGIC;
    signal grp_chi_fu_384_A_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_chi_fu_384_A_ce0 : STD_LOGIC;
    signal grp_chi_fu_384_A_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_chi_fu_384_A_ce1 : STD_LOGIC;
    signal grp_chi_fu_384_A_we1 : STD_LOGIC;
    signal grp_chi_fu_384_A_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal instance_byteIOIndex_1_reg_204 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal i_0_reg_216 : STD_LOGIC_VECTOR (32 downto 0);
    signal curData_0_idx_reg_228 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_0_i_reg_240 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal j_0_i_reg_251 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal indexRound_assign_reg_263 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal ap_phi_mux_indvar_flatten_phi_fu_279_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal ap_phi_mux_x_0_i_phi_fu_290_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_y_0_i_phi_fu_302_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_i_0_i2_phi_fu_324_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp2_stage0 : BOOLEAN;
    signal instance_byteIOIndex_2_reg_342 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_KeccakP1600_ExtractB_fu_355_ap_start_reg : STD_LOGIC := '0';
    signal grp_pi_fu_374_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal grp_theta_fu_379_ap_start_reg : STD_LOGIC := '0';
    signal grp_chi_fu_384_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal zext_ln270_fu_424_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln272_fu_458_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln353_3_fu_615_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp1_stage1 : BOOLEAN;
    signal zext_ln382_fu_675_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln280_fu_727_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln282_2_fu_779_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln272_fu_489_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln382_fu_680_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal dataByteLen_cast_fu_389_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln271_fu_449_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln272_fu_453_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln272_fu_467_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln272_9_fu_471_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln272_3_fu_463_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln272_4_fu_479_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln272_fu_483_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln353_1_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln353_1_fu_552_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln353_3_fu_558_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln353_2_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln353_2_fu_575_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln353_4_fu_580_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln353_fu_566_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln353_1_fu_587_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln353_fu_599_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln2_fu_591_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln353_2_fu_605_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln353_3_fu_609_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp1_stage2 : BOOLEAN;
    signal zext_ln353_5_fu_631_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln353_4_fu_627_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln353_fu_641_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln353_6_fu_647_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lshr_ln353_fu_651_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln353_fu_635_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln353_fu_657_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln281_fu_705_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_20_fu_699_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln282_5_fu_742_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln282_fu_749_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lshr_ln282_fu_753_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln281_fu_770_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln282_mid2_fu_763_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln282_fu_773_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln322_fu_784_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln323_fu_793_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln323_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal partialBlock_20_fu_804_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln325_1_fu_822_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln325_fu_818_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_block_pp1_stage1_subdone : BOOLEAN;
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;
    signal ap_idle_pp2 : STD_LOGIC;
    signal ap_enable_pp2 : STD_LOGIC;

    component KeccakP1600_ExtractB IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        state_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        state_ce0 : OUT STD_LOGIC;
        state_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        data_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        data_0_ce0 : OUT STD_LOGIC;
        data_0_we0 : OUT STD_LOGIC;
        data_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        data_1_ce0 : OUT STD_LOGIC;
        data_1_we0 : OUT STD_LOGIC;
        data_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        data_2_ce0 : OUT STD_LOGIC;
        data_2_we0 : OUT STD_LOGIC;
        data_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        data_3_ce0 : OUT STD_LOGIC;
        data_3_we0 : OUT STD_LOGIC;
        data_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        data_offset : IN STD_LOGIC_VECTOR (63 downto 0);
        offset : IN STD_LOGIC_VECTOR (31 downto 0);
        length_r : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component pi IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        A_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        A_ce0 : OUT STD_LOGIC;
        A_we0 : OUT STD_LOGIC;
        A_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        A_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        A_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        A_ce1 : OUT STD_LOGIC;
        A_we1 : OUT STD_LOGIC;
        A_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        A_q1 : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component theta IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        A_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        A_ce0 : OUT STD_LOGIC;
        A_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        A_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        A_ce1 : OUT STD_LOGIC;
        A_we1 : OUT STD_LOGIC;
        A_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        A_q1 : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component chi IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        A_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        A_ce0 : OUT STD_LOGIC;
        A_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        A_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        A_ce1 : OUT STD_LOGIC;
        A_we1 : OUT STD_LOGIC;
        A_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        A_q1 : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component KeccakP1600OnWordeOg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component KeccakP1600OnWordfYi IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component pi_tempA IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (63 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (63 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    KeccakRhoOffsets_U : component KeccakP1600OnWordeOg
    generic map (
        DataWidth => 6,
        AddressRange => 25,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => KeccakRhoOffsets_address0,
        ce0 => KeccakRhoOffsets_ce0,
        q0 => KeccakRhoOffsets_q0);

    KeccakRoundConstants_U : component KeccakP1600OnWordfYi
    generic map (
        DataWidth => 64,
        AddressRange => 24,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => KeccakRoundConstants_address0,
        ce0 => KeccakRoundConstants_ce0,
        q0 => KeccakRoundConstants_q0);

    stateAsWords_U : component pi_tempA
    generic map (
        DataWidth => 64,
        AddressRange => 25,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => stateAsWords_address0,
        ce0 => stateAsWords_ce0,
        we0 => stateAsWords_we0,
        d0 => stateAsWords_d0,
        q0 => stateAsWords_q0,
        address1 => stateAsWords_address1,
        ce1 => stateAsWords_ce1,
        we1 => stateAsWords_we1,
        d1 => stateAsWords_d1,
        q1 => stateAsWords_q1);

    grp_KeccakP1600_ExtractB_fu_355 : component KeccakP1600_ExtractB
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_KeccakP1600_ExtractB_fu_355_ap_start,
        ap_done => grp_KeccakP1600_ExtractB_fu_355_ap_done,
        ap_idle => grp_KeccakP1600_ExtractB_fu_355_ap_idle,
        ap_ready => grp_KeccakP1600_ExtractB_fu_355_ap_ready,
        state_address0 => grp_KeccakP1600_ExtractB_fu_355_state_address0,
        state_ce0 => grp_KeccakP1600_ExtractB_fu_355_state_ce0,
        state_q0 => instance_state_q0,
        data_0_address0 => grp_KeccakP1600_ExtractB_fu_355_data_0_address0,
        data_0_ce0 => grp_KeccakP1600_ExtractB_fu_355_data_0_ce0,
        data_0_we0 => grp_KeccakP1600_ExtractB_fu_355_data_0_we0,
        data_0_d0 => grp_KeccakP1600_ExtractB_fu_355_data_0_d0,
        data_1_address0 => grp_KeccakP1600_ExtractB_fu_355_data_1_address0,
        data_1_ce0 => grp_KeccakP1600_ExtractB_fu_355_data_1_ce0,
        data_1_we0 => grp_KeccakP1600_ExtractB_fu_355_data_1_we0,
        data_1_d0 => grp_KeccakP1600_ExtractB_fu_355_data_1_d0,
        data_2_address0 => grp_KeccakP1600_ExtractB_fu_355_data_2_address0,
        data_2_ce0 => grp_KeccakP1600_ExtractB_fu_355_data_2_ce0,
        data_2_we0 => grp_KeccakP1600_ExtractB_fu_355_data_2_we0,
        data_2_d0 => grp_KeccakP1600_ExtractB_fu_355_data_2_d0,
        data_3_address0 => grp_KeccakP1600_ExtractB_fu_355_data_3_address0,
        data_3_ce0 => grp_KeccakP1600_ExtractB_fu_355_data_3_ce0,
        data_3_we0 => grp_KeccakP1600_ExtractB_fu_355_data_3_we0,
        data_3_d0 => grp_KeccakP1600_ExtractB_fu_355_data_3_d0,
        data_offset => curData_0_idx_reg_228,
        offset => instance_byteIOIndex_2_reg_342,
        length_r => partialBlock_21_reg_1017);

    grp_pi_fu_374 : component pi
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_pi_fu_374_ap_start,
        ap_done => grp_pi_fu_374_ap_done,
        ap_idle => grp_pi_fu_374_ap_idle,
        ap_ready => grp_pi_fu_374_ap_ready,
        A_address0 => grp_pi_fu_374_A_address0,
        A_ce0 => grp_pi_fu_374_A_ce0,
        A_we0 => grp_pi_fu_374_A_we0,
        A_d0 => grp_pi_fu_374_A_d0,
        A_q0 => stateAsWords_q0,
        A_address1 => grp_pi_fu_374_A_address1,
        A_ce1 => grp_pi_fu_374_A_ce1,
        A_we1 => grp_pi_fu_374_A_we1,
        A_d1 => grp_pi_fu_374_A_d1,
        A_q1 => stateAsWords_q1);

    grp_theta_fu_379 : component theta
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_theta_fu_379_ap_start,
        ap_done => grp_theta_fu_379_ap_done,
        ap_idle => grp_theta_fu_379_ap_idle,
        ap_ready => grp_theta_fu_379_ap_ready,
        A_address0 => grp_theta_fu_379_A_address0,
        A_ce0 => grp_theta_fu_379_A_ce0,
        A_q0 => stateAsWords_q0,
        A_address1 => grp_theta_fu_379_A_address1,
        A_ce1 => grp_theta_fu_379_A_ce1,
        A_we1 => grp_theta_fu_379_A_we1,
        A_d1 => grp_theta_fu_379_A_d1,
        A_q1 => stateAsWords_q1);

    grp_chi_fu_384 : component chi
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_chi_fu_384_ap_start,
        ap_done => grp_chi_fu_384_ap_done,
        ap_idle => grp_chi_fu_384_ap_idle,
        ap_ready => grp_chi_fu_384_ap_ready,
        A_address0 => grp_chi_fu_384_A_address0,
        A_ce0 => grp_chi_fu_384_A_ce0,
        A_q0 => stateAsWords_q0,
        A_address1 => grp_chi_fu_384_A_address1,
        A_ce1 => grp_chi_fu_384_A_ce1,
        A_we1 => grp_chi_fu_384_A_we1,
        A_d1 => grp_chi_fu_384_A_d1,
        A_q1 => stateAsWords_q1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state9) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif (((grp_theta_fu_379_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if ((((ap_const_boolean_0 = ap_block_pp1_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage2)) or ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                elsif (((grp_theta_fu_379_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp2_exit_iter0_state19) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
                    ap_enable_reg_pp2_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln293_fu_496_p2 = ap_const_lv1_1))) then 
                    ap_enable_reg_pp2_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp2_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp2_exit_iter0_state19)) then 
                        ap_enable_reg_pp2_iter1 <= (ap_const_logic_1 xor ap_condition_pp2_exit_iter0_state19);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp2_stage0_subdone)) then 
                    ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln293_fu_496_p2 = ap_const_lv1_1))) then 
                    ap_enable_reg_pp2_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_KeccakP1600_ExtractB_fu_355_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_KeccakP1600_ExtractB_fu_355_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
                    grp_KeccakP1600_ExtractB_fu_355_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_KeccakP1600_ExtractB_fu_355_ap_ready = ap_const_logic_1)) then 
                    grp_KeccakP1600_ExtractB_fu_355_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_chi_fu_384_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_chi_fu_384_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                    grp_chi_fu_384_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_chi_fu_384_ap_ready = ap_const_logic_1)) then 
                    grp_chi_fu_384_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_pi_fu_374_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_pi_fu_374_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                    grp_pi_fu_374_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_pi_fu_374_ap_ready = ap_const_logic_1)) then 
                    grp_pi_fu_374_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_theta_fu_379_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_theta_fu_379_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln293_fu_496_p2 = ap_const_lv1_0))) then 
                    grp_theta_fu_379_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_theta_fu_379_ap_ready = ap_const_logic_1)) then 
                    grp_theta_fu_379_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    curData_0_idx_reg_228_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_KeccakP1600_ExtractB_fu_355_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state24))) then 
                curData_0_idx_reg_228 <= add_ln331_reg_1032;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                curData_0_idx_reg_228 <= ap_const_lv64_0;
            end if; 
        end if;
    end process;

    i_0_i2_reg_320_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln293_fu_496_p2 = ap_const_lv1_1))) then 
                i_0_i2_reg_320 <= ap_const_lv5_0;
            elsif (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (icmp_ln280_reg_971 = ap_const_lv1_0))) then 
                i_0_i2_reg_320 <= select_ln280_2_reg_985;
            end if; 
        end if;
    end process;

    i_0_i_reg_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                i_0_i_reg_240 <= i_19_reg_871;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln304_fu_401_p2 = ap_const_lv1_1) and (icmp_ln305_fu_406_p2 = ap_const_lv1_1))) then 
                i_0_i_reg_240 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    i_0_reg_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_KeccakP1600_ExtractB_fu_355_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state24))) then 
                i_0_reg_216 <= i_reg_1022;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_reg_216 <= ap_const_lv33_0;
            end if; 
        end if;
    end process;

    indexRound_assign_reg_263_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln269_fu_412_p2 = ap_const_lv1_1))) then 
                indexRound_assign_reg_263 <= ap_const_lv5_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
                indexRound_assign_reg_263 <= i_21_reg_903;
            end if; 
        end if;
    end process;

    indvar_flatten7_reg_309_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln293_fu_496_p2 = ap_const_lv1_1))) then 
                indvar_flatten7_reg_309 <= ap_const_lv8_0;
            elsif (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (icmp_ln280_fu_687_p2 = ap_const_lv1_0))) then 
                indvar_flatten7_reg_309 <= add_ln280_fu_693_p2;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_275_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln352_reg_908 = ap_const_lv1_0))) then 
                indvar_flatten_reg_275 <= add_ln352_reg_912;
            elsif (((grp_theta_fu_379_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                indvar_flatten_reg_275 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    instance_byteIOIndex_1_reg_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_KeccakP1600_ExtractB_fu_355_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state24))) then 
                instance_byteIOIndex_1_reg_204 <= add_ln332_reg_1027;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                instance_byteIOIndex_1_reg_204 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    instance_byteIOIndex_2_reg_342_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state22) and (icmp_ln305_reg_863 = ap_const_lv1_1))) then 
                instance_byteIOIndex_2_reg_342 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln304_fu_401_p2 = ap_const_lv1_1) and (icmp_ln305_fu_406_p2 = ap_const_lv1_0))) then 
                instance_byteIOIndex_2_reg_342 <= instance_byteIOIndex_1_reg_204;
            end if; 
        end if;
    end process;

    j_0_i5_reg_331_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln293_fu_496_p2 = ap_const_lv1_1))) then 
                j_0_i5_reg_331 <= ap_const_lv4_0;
            elsif (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (icmp_ln280_fu_687_p2 = ap_const_lv1_0))) then 
                j_0_i5_reg_331 <= j_9_fu_736_p2;
            end if; 
        end if;
    end process;

    j_0_i_reg_251_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                j_0_i_reg_251 <= j_reg_889;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln269_fu_412_p2 = ap_const_lv1_0))) then 
                j_0_i_reg_251 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    x_0_i_reg_286_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln352_reg_908 = ap_const_lv1_0))) then 
                x_0_i_reg_286 <= select_ln353_2_reg_935;
            elsif (((grp_theta_fu_379_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                x_0_i_reg_286 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    y_0_i_reg_298_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln352_reg_908 = ap_const_lv1_0))) then 
                y_0_i_reg_298 <= y_reg_961;
            elsif (((grp_theta_fu_379_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                y_0_i_reg_298 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state23)) then
                add_ln331_reg_1032 <= add_ln331_fu_838_p2;
                add_ln332_reg_1027 <= add_ln332_fu_832_p2;
                i_reg_1022 <= i_fu_826_p2;
                partialBlock_21_reg_1017 <= partialBlock_21_fu_810_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                add_ln352_reg_912 <= add_ln352_fu_514_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                i_19_reg_871 <= i_19_fu_418_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                i_21_reg_903 <= i_21_fu_502_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then
                icmp_ln280_reg_971 <= icmp_ln280_fu_687_p2;
                icmp_ln280_reg_971_pp2_iter1_reg <= icmp_ln280_reg_971;
                select_ln280_2_reg_985_pp2_iter1_reg <= select_ln280_2_reg_985;
                select_ln280_reg_980_pp2_iter1_reg <= select_ln280_reg_980;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln304_fu_401_p2 = ap_const_lv1_1))) then
                icmp_ln305_reg_863 <= icmp_ln305_fu_406_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln352_fu_508_p2 = ap_const_lv1_0))) then
                icmp_ln352_1_reg_922 <= icmp_ln352_1_fu_526_p2;
                select_ln353_1_reg_927 <= select_ln353_1_fu_532_p3;
                x_reg_917 <= x_fu_520_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                icmp_ln352_reg_908 <= icmp_ln352_fu_508_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage1) and (ap_const_boolean_0 = ap_block_pp1_stage1_11001) and (icmp_ln352_reg_908 = ap_const_lv1_0))) then
                icmp_ln353_reg_945 <= icmp_ln353_fu_621_p2;
                stateAsWords_addr_3_reg_950 <= zext_ln353_3_fu_615_p1(5 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                j_reg_889 <= j_fu_443_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state22)) then
                partialBlock_reg_1011 <= partialBlock_fu_788_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (icmp_ln280_fu_687_p2 = ap_const_lv1_0))) then
                select_ln280_2_reg_985 <= select_ln280_2_fu_719_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (icmp_ln280_fu_687_p2 = ap_const_lv1_0))) then
                select_ln280_reg_980 <= select_ln280_fu_711_p3;
                trunc_ln282_reg_996 <= trunc_ln282_fu_732_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage1_11001) and (icmp_ln352_reg_908 = ap_const_lv1_0))) then
                select_ln353_2_reg_935 <= select_ln353_2_fu_540_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage2) and (icmp_ln352_reg_908 = ap_const_lv1_0))) then
                select_ln353_reg_956 <= select_ln353_fu_663_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln269_fu_412_p2 = ap_const_lv1_0))) then
                    shl_ln_reg_881(7 downto 3) <= shl_ln_fu_429_p3(7 downto 3);
                stateAsWords_addr_1_reg_876 <= zext_ln270_fu_424_p1(5 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (icmp_ln280_reg_971 = ap_const_lv1_0))) then
                trunc_ln282_2_reg_1006 <= trunc_ln282_2_fu_759_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage2) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln352_reg_908 = ap_const_lv1_0))) then
                y_reg_961 <= y_fu_670_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    zext_ln304_reg_850(8 downto 0) <= zext_ln304_fu_393_p1(8 downto 0);
                    zext_ln322_reg_855(8 downto 0) <= zext_ln322_fu_397_p1(8 downto 0);
            end if;
        end if;
    end process;
    zext_ln304_reg_850(32 downto 9) <= "000000000000000000000000";
    zext_ln322_reg_855(31 downto 9) <= "00000000000000000000000";
    shl_ln_reg_881(2 downto 0) <= "000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln305_fu_406_p2, ap_CS_fsm_state2, icmp_ln304_fu_401_p2, icmp_ln269_fu_412_p2, ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln271_fu_437_p2, icmp_ln293_fu_496_p2, ap_CS_fsm_state7, icmp_ln352_fu_508_p2, ap_enable_reg_pp1_iter0, icmp_ln280_fu_687_p2, ap_enable_reg_pp2_iter0, ap_CS_fsm_state8, grp_theta_fu_379_ap_done, ap_block_pp1_stage0_subdone, ap_block_pp1_stage2_subdone, ap_block_pp2_stage0_subdone, ap_enable_reg_pp2_iter1, ap_enable_reg_pp2_iter2, grp_KeccakP1600_ExtractB_fu_355_ap_done, grp_pi_fu_374_ap_done, grp_chi_fu_384_ap_done, ap_CS_fsm_state24, ap_CS_fsm_state14, ap_CS_fsm_state16, ap_block_pp1_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln304_fu_401_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln304_fu_401_p2 = ap_const_lv1_1) and (icmp_ln305_fu_406_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state22;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln269_fu_412_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln271_fu_437_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln293_fu_496_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                if (((grp_theta_fu_379_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_pp1_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln352_fu_508_p2 = ap_const_lv1_1))) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage1;
                elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln352_fu_508_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_pp1_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp1_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage1;
                end if;
            when ap_ST_fsm_pp1_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp1_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage2;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                if (((grp_pi_fu_374_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                if (((grp_chi_fu_384_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then
                    ap_NS_fsm <= ap_ST_fsm_state17;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_pp2_stage0 => 
                if ((not(((ap_enable_reg_pp2_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (icmp_ln280_fu_687_p2 = ap_const_lv1_1))) and not(((ap_enable_reg_pp2_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_enable_reg_pp2_iter2 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
                elsif ((((ap_enable_reg_pp2_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_enable_reg_pp2_iter2 = ap_const_logic_1)) or ((ap_enable_reg_pp2_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (icmp_ln280_fu_687_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state22;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
                end if;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                if (((grp_KeccakP1600_ExtractB_fu_355_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state24))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state24;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    KeccakRhoOffsets_address0 <= zext_ln353_3_fu_615_p1(5 - 1 downto 0);

    KeccakRhoOffsets_ce0_assign_proc : process(ap_enable_reg_pp1_iter0, ap_CS_fsm_pp1_stage1, ap_block_pp1_stage1_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage1_11001))) then 
            KeccakRhoOffsets_ce0 <= ap_const_logic_1;
        else 
            KeccakRhoOffsets_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    KeccakRoundConstants_address0 <= zext_ln382_fu_675_p1(5 - 1 downto 0);

    KeccakRoundConstants_ce0_assign_proc : process(ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            KeccakRoundConstants_ce0 <= ap_const_logic_1;
        else 
            KeccakRoundConstants_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln272_fu_453_p2 <= std_logic_vector(unsigned(shl_ln_reg_881) + unsigned(zext_ln271_fu_449_p1));
    add_ln280_fu_693_p2 <= std_logic_vector(unsigned(indvar_flatten7_reg_309) + unsigned(ap_const_lv8_1));
    add_ln282_fu_773_p2 <= std_logic_vector(unsigned(zext_ln281_fu_770_p1) + unsigned(shl_ln282_mid2_fu_763_p3));
    add_ln323_fu_793_p2 <= std_logic_vector(unsigned(partialBlock_reg_1011) + unsigned(instance_byteIOIndex_2_reg_342));
    add_ln331_fu_838_p2 <= std_logic_vector(unsigned(curData_0_idx_reg_228) + unsigned(zext_ln325_fu_818_p1));
    add_ln332_fu_832_p2 <= std_logic_vector(unsigned(partialBlock_21_fu_810_p3) + unsigned(instance_byteIOIndex_2_reg_342));
    add_ln352_fu_514_p2 <= std_logic_vector(unsigned(ap_phi_mux_indvar_flatten_phi_fu_279_p4) + unsigned(ap_const_lv5_1));
    add_ln353_1_fu_552_p2 <= std_logic_vector(unsigned(select_ln353_2_fu_540_p3) + unsigned(ap_const_lv3_3));
    add_ln353_2_fu_575_p2 <= std_logic_vector(unsigned(select_ln353_1_reg_927) + unsigned(ap_const_lv3_3));
    add_ln353_3_fu_609_p2 <= std_logic_vector(unsigned(shl_ln2_fu_591_p3) + unsigned(zext_ln353_2_fu_605_p1));
    add_ln353_fu_599_p2 <= std_logic_vector(unsigned(zext_ln353_fu_566_p1) + unsigned(zext_ln353_1_fu_587_p1));
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(8);
    ap_CS_fsm_pp1_stage1 <= ap_CS_fsm(9);
    ap_CS_fsm_pp1_stage2 <= ap_CS_fsm(10);
    ap_CS_fsm_pp2_stage0 <= ap_CS_fsm(17);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state13 <= ap_CS_fsm(11);
    ap_CS_fsm_state14 <= ap_CS_fsm(12);
    ap_CS_fsm_state15 <= ap_CS_fsm(13);
    ap_CS_fsm_state16 <= ap_CS_fsm(14);
    ap_CS_fsm_state17 <= ap_CS_fsm(15);
    ap_CS_fsm_state18 <= ap_CS_fsm(16);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state22 <= ap_CS_fsm(18);
    ap_CS_fsm_state23 <= ap_CS_fsm(19);
    ap_CS_fsm_state24 <= ap_CS_fsm(20);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp2_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp2_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp2_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp1_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp1_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp1_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp2_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp2_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp2_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp1_exit_iter0_state9_assign_proc : process(icmp_ln352_fu_508_p2)
    begin
        if ((icmp_ln352_fu_508_p2 = ap_const_lv1_1)) then 
            ap_condition_pp1_exit_iter0_state9 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state9 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp2_exit_iter0_state19_assign_proc : process(icmp_ln280_fu_687_p2)
    begin
        if ((icmp_ln280_fu_687_p2 = ap_const_lv1_1)) then 
            ap_condition_pp2_exit_iter0_state19 <= ap_const_logic_1;
        else 
            ap_condition_pp2_exit_iter0_state19 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln304_fu_401_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln304_fu_401_p2 = ap_const_lv1_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);
    ap_enable_pp2 <= (ap_idle_pp2 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter1)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp2_assign_proc : process(ap_enable_reg_pp2_iter0, ap_enable_reg_pp2_iter1, ap_enable_reg_pp2_iter2)
    begin
        if (((ap_enable_reg_pp2_iter2 = ap_const_logic_0) and (ap_enable_reg_pp2_iter1 = ap_const_logic_0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_0))) then 
            ap_idle_pp2 <= ap_const_logic_1;
        else 
            ap_idle_pp2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_i_0_i2_phi_fu_324_p4_assign_proc : process(i_0_i2_reg_320, icmp_ln280_reg_971, ap_CS_fsm_pp2_stage0, select_ln280_2_reg_985, ap_enable_reg_pp2_iter1, ap_block_pp2_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp2_stage0) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (icmp_ln280_reg_971 = ap_const_lv1_0))) then 
            ap_phi_mux_i_0_i2_phi_fu_324_p4 <= select_ln280_2_reg_985;
        else 
            ap_phi_mux_i_0_i2_phi_fu_324_p4 <= i_0_i2_reg_320;
        end if; 
    end process;


    ap_phi_mux_indvar_flatten_phi_fu_279_p4_assign_proc : process(indvar_flatten_reg_275, icmp_ln352_reg_908, ap_CS_fsm_pp1_stage0, add_ln352_reg_912, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (icmp_ln352_reg_908 = ap_const_lv1_0))) then 
            ap_phi_mux_indvar_flatten_phi_fu_279_p4 <= add_ln352_reg_912;
        else 
            ap_phi_mux_indvar_flatten_phi_fu_279_p4 <= indvar_flatten_reg_275;
        end if; 
    end process;


    ap_phi_mux_x_0_i_phi_fu_290_p4_assign_proc : process(x_0_i_reg_286, icmp_ln352_reg_908, ap_CS_fsm_pp1_stage0, select_ln353_2_reg_935, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (icmp_ln352_reg_908 = ap_const_lv1_0))) then 
            ap_phi_mux_x_0_i_phi_fu_290_p4 <= select_ln353_2_reg_935;
        else 
            ap_phi_mux_x_0_i_phi_fu_290_p4 <= x_0_i_reg_286;
        end if; 
    end process;


    ap_phi_mux_y_0_i_phi_fu_302_p4_assign_proc : process(y_0_i_reg_298, icmp_ln352_reg_908, ap_CS_fsm_pp1_stage0, y_reg_961, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (icmp_ln352_reg_908 = ap_const_lv1_0))) then 
            ap_phi_mux_y_0_i_phi_fu_302_p4 <= y_reg_961;
        else 
            ap_phi_mux_y_0_i_phi_fu_302_p4 <= y_0_i_reg_298;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln304_fu_401_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln304_fu_401_p2 = ap_const_lv1_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

        dataByteLen_cast_fu_389_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(dataByteLen),9));

    data_0_address0 <= grp_KeccakP1600_ExtractB_fu_355_data_0_address0;
    data_0_ce0 <= grp_KeccakP1600_ExtractB_fu_355_data_0_ce0;
    data_0_d0 <= grp_KeccakP1600_ExtractB_fu_355_data_0_d0;
    data_0_we0 <= grp_KeccakP1600_ExtractB_fu_355_data_0_we0;
    data_1_address0 <= grp_KeccakP1600_ExtractB_fu_355_data_1_address0;
    data_1_ce0 <= grp_KeccakP1600_ExtractB_fu_355_data_1_ce0;
    data_1_d0 <= grp_KeccakP1600_ExtractB_fu_355_data_1_d0;
    data_1_we0 <= grp_KeccakP1600_ExtractB_fu_355_data_1_we0;
    data_2_address0 <= grp_KeccakP1600_ExtractB_fu_355_data_2_address0;
    data_2_ce0 <= grp_KeccakP1600_ExtractB_fu_355_data_2_ce0;
    data_2_d0 <= grp_KeccakP1600_ExtractB_fu_355_data_2_d0;
    data_2_we0 <= grp_KeccakP1600_ExtractB_fu_355_data_2_we0;
    data_3_address0 <= grp_KeccakP1600_ExtractB_fu_355_data_3_address0;
    data_3_ce0 <= grp_KeccakP1600_ExtractB_fu_355_data_3_ce0;
    data_3_d0 <= grp_KeccakP1600_ExtractB_fu_355_data_3_d0;
    data_3_we0 <= grp_KeccakP1600_ExtractB_fu_355_data_3_we0;
    grp_KeccakP1600_ExtractB_fu_355_ap_start <= grp_KeccakP1600_ExtractB_fu_355_ap_start_reg;
    grp_chi_fu_384_ap_start <= grp_chi_fu_384_ap_start_reg;
    grp_pi_fu_374_ap_start <= grp_pi_fu_374_ap_start_reg;
    grp_theta_fu_379_ap_start <= grp_theta_fu_379_ap_start_reg;
    i_19_fu_418_p2 <= std_logic_vector(unsigned(i_0_i_reg_240) + unsigned(ap_const_lv5_1));
    i_20_fu_699_p2 <= std_logic_vector(unsigned(ap_const_lv5_1) + unsigned(ap_phi_mux_i_0_i2_phi_fu_324_p4));
    i_21_fu_502_p2 <= std_logic_vector(unsigned(indexRound_assign_reg_263) + unsigned(ap_const_lv5_1));
    i_fu_826_p2 <= std_logic_vector(unsigned(i_0_reg_216) + unsigned(zext_ln325_1_fu_822_p1));
    icmp_ln269_fu_412_p2 <= "1" when (i_0_i_reg_240 = ap_const_lv5_19) else "0";
    icmp_ln271_fu_437_p2 <= "1" when (j_0_i_reg_251 = ap_const_lv4_8) else "0";
    icmp_ln280_fu_687_p2 <= "1" when (indvar_flatten7_reg_309 = ap_const_lv8_C8) else "0";
    icmp_ln281_fu_705_p2 <= "1" when (j_0_i5_reg_331 = ap_const_lv4_8) else "0";
    icmp_ln293_fu_496_p2 <= "1" when (indexRound_assign_reg_263 = ap_const_lv5_18) else "0";
    icmp_ln304_fu_401_p2 <= "1" when (unsigned(i_0_reg_216) < unsigned(zext_ln304_reg_850)) else "0";
    icmp_ln305_fu_406_p2 <= "1" when (instance_byteIOIndex_1_reg_204 = ap_const_lv32_A8) else "0";
    icmp_ln323_fu_798_p2 <= "1" when (unsigned(add_ln323_fu_793_p2) > unsigned(ap_const_lv32_A8)) else "0";
    icmp_ln352_1_fu_526_p2 <= "1" when (ap_phi_mux_y_0_i_phi_fu_302_p4 = ap_const_lv3_5) else "0";
    icmp_ln352_fu_508_p2 <= "1" when (ap_phi_mux_indvar_flatten_phi_fu_279_p4 = ap_const_lv5_19) else "0";
    icmp_ln353_1_fu_546_p2 <= "1" when (unsigned(select_ln353_2_fu_540_p3) < unsigned(ap_const_lv3_5)) else "0";
    icmp_ln353_2_fu_570_p2 <= "1" when (unsigned(select_ln353_1_reg_927) < unsigned(ap_const_lv3_5)) else "0";
    icmp_ln353_fu_621_p2 <= "1" when (add_ln353_3_fu_609_p2 = ap_const_lv5_0) else "0";

    instance_state_address0_assign_proc : process(ap_CS_fsm_state4, ap_enable_reg_pp2_iter2, grp_KeccakP1600_ExtractB_fu_355_state_address0, ap_CS_fsm_state24, ap_block_pp2_stage0, zext_ln272_fu_458_p1, zext_ln282_2_fu_779_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp2_stage0) and (ap_enable_reg_pp2_iter2 = ap_const_logic_1))) then 
            instance_state_address0 <= zext_ln282_2_fu_779_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            instance_state_address0 <= zext_ln272_fu_458_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            instance_state_address0 <= grp_KeccakP1600_ExtractB_fu_355_state_address0;
        else 
            instance_state_address0 <= "XXXXXXXX";
        end if; 
    end process;


    instance_state_ce0_assign_proc : process(ap_CS_fsm_state4, ap_block_pp2_stage0_11001, ap_enable_reg_pp2_iter2, grp_KeccakP1600_ExtractB_fu_355_state_ce0, ap_CS_fsm_state24)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_enable_reg_pp2_iter2 = ap_const_logic_1)))) then 
            instance_state_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            instance_state_ce0 <= grp_KeccakP1600_ExtractB_fu_355_state_ce0;
        else 
            instance_state_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    instance_state_d0 <= trunc_ln282_2_reg_1006;

    instance_state_we0_assign_proc : process(ap_block_pp2_stage0_11001, icmp_ln280_reg_971_pp2_iter1_reg, ap_enable_reg_pp2_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_enable_reg_pp2_iter2 = ap_const_logic_1) and (icmp_ln280_reg_971_pp2_iter1_reg = ap_const_lv1_0))) then 
            instance_state_we0 <= ap_const_logic_1;
        else 
            instance_state_we0 <= ap_const_logic_0;
        end if; 
    end process;

    j_9_fu_736_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(select_ln280_fu_711_p3));
    j_fu_443_p2 <= std_logic_vector(unsigned(j_0_i_reg_251) + unsigned(ap_const_lv4_1));
    lshr_ln282_fu_753_p2 <= std_logic_vector(shift_right(unsigned(stateAsWords_q1),to_integer(unsigned('0' & zext_ln282_fu_749_p1(31-1 downto 0)))));
    lshr_ln353_fu_651_p2 <= std_logic_vector(shift_right(unsigned(stateAsWords_q1),to_integer(unsigned('0' & zext_ln353_6_fu_647_p1(31-1 downto 0)))));
    or_ln272_fu_489_p2 <= (stateAsWords_q0 or shl_ln272_fu_483_p2);
    partialBlock_20_fu_804_p2 <= std_logic_vector(unsigned(ap_const_lv32_A8) - unsigned(instance_byteIOIndex_2_reg_342));
    partialBlock_21_fu_810_p3 <= 
        partialBlock_20_fu_804_p2 when (icmp_ln323_fu_798_p2(0) = '1') else 
        partialBlock_reg_1011;
    partialBlock_fu_788_p2 <= std_logic_vector(unsigned(zext_ln322_reg_855) - unsigned(trunc_ln322_fu_784_p1));
    select_ln280_2_fu_719_p3 <= 
        i_20_fu_699_p2 when (icmp_ln281_fu_705_p2(0) = '1') else 
        ap_phi_mux_i_0_i2_phi_fu_324_p4;
    select_ln280_fu_711_p3 <= 
        ap_const_lv4_0 when (icmp_ln281_fu_705_p2(0) = '1') else 
        j_0_i5_reg_331;
    select_ln353_1_fu_532_p3 <= 
        ap_const_lv3_0 when (icmp_ln352_1_fu_526_p2(0) = '1') else 
        ap_phi_mux_y_0_i_phi_fu_302_p4;
    select_ln353_2_fu_540_p3 <= 
        x_reg_917 when (icmp_ln352_1_reg_922(0) = '1') else 
        x_0_i_reg_286;
    select_ln353_3_fu_558_p3 <= 
        select_ln353_2_fu_540_p3 when (icmp_ln353_1_fu_546_p2(0) = '1') else 
        add_ln353_1_fu_552_p2;
    select_ln353_4_fu_580_p3 <= 
        select_ln353_1_reg_927 when (icmp_ln353_2_fu_570_p2(0) = '1') else 
        add_ln353_2_fu_575_p2;
    select_ln353_fu_663_p3 <= 
        stateAsWords_q0 when (icmp_ln353_reg_945(0) = '1') else 
        xor_ln353_fu_657_p2;
    shl_ln272_9_fu_471_p3 <= (trunc_ln272_fu_467_p1 & ap_const_lv3_0);
    shl_ln272_fu_483_p2 <= std_logic_vector(shift_left(unsigned(zext_ln272_3_fu_463_p1),to_integer(unsigned('0' & zext_ln272_4_fu_479_p1(31-1 downto 0)))));
    shl_ln282_5_fu_742_p3 <= (trunc_ln282_reg_996 & ap_const_lv3_0);
    shl_ln282_mid2_fu_763_p3 <= (select_ln280_2_reg_985_pp2_iter1_reg & ap_const_lv3_0);
    shl_ln2_fu_591_p3 <= (select_ln353_4_fu_580_p3 & ap_const_lv2_0);
    shl_ln353_fu_635_p2 <= std_logic_vector(shift_left(unsigned(stateAsWords_q1),to_integer(unsigned('0' & zext_ln353_5_fu_631_p1(31-1 downto 0)))));
    shl_ln_fu_429_p3 <= (i_0_i_reg_240 & ap_const_lv3_0);

    stateAsWords_address0_assign_proc : process(ap_CS_fsm_state3, stateAsWords_addr_1_reg_876, ap_CS_fsm_state4, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, ap_CS_fsm_pp1_stage1, stateAsWords_addr_3_reg_950, ap_CS_fsm_state8, ap_enable_reg_pp1_iter1, grp_pi_fu_374_A_address0, grp_theta_fu_379_A_address0, grp_chi_fu_384_A_address0, ap_CS_fsm_state5, ap_block_pp1_stage0, ap_CS_fsm_state14, ap_CS_fsm_state16, zext_ln270_fu_424_p1, ap_block_pp1_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            stateAsWords_address0 <= stateAsWords_addr_3_reg_950;
        elsif (((ap_const_boolean_0 = ap_block_pp1_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) then 
            stateAsWords_address0 <= ap_const_lv64_0(5 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            stateAsWords_address0 <= stateAsWords_addr_1_reg_876;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            stateAsWords_address0 <= zext_ln270_fu_424_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            stateAsWords_address0 <= grp_chi_fu_384_A_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            stateAsWords_address0 <= grp_theta_fu_379_A_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            stateAsWords_address0 <= grp_pi_fu_374_A_address0;
        else 
            stateAsWords_address0 <= "XXXXX";
        end if; 
    end process;


    stateAsWords_address1_assign_proc : process(ap_enable_reg_pp1_iter0, ap_CS_fsm_pp1_stage1, ap_CS_fsm_state17, ap_CS_fsm_pp2_stage0, ap_enable_reg_pp2_iter0, ap_CS_fsm_state8, grp_pi_fu_374_A_address1, grp_theta_fu_379_A_address1, grp_chi_fu_384_A_address1, ap_CS_fsm_state18, ap_block_pp2_stage0, ap_CS_fsm_state14, ap_CS_fsm_state16, zext_ln353_3_fu_615_p1, ap_block_pp1_stage1, zext_ln280_fu_727_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp2_stage0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
            stateAsWords_address1 <= zext_ln280_fu_727_p1(5 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            stateAsWords_address1 <= ap_const_lv64_0(5 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp1_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) then 
            stateAsWords_address1 <= zext_ln353_3_fu_615_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            stateAsWords_address1 <= grp_chi_fu_384_A_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            stateAsWords_address1 <= grp_theta_fu_379_A_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            stateAsWords_address1 <= grp_pi_fu_374_A_address1;
        else 
            stateAsWords_address1 <= "XXXXX";
        end if; 
    end process;


    stateAsWords_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter0, ap_CS_fsm_pp1_stage1, ap_block_pp1_stage1_11001, ap_CS_fsm_state8, ap_enable_reg_pp1_iter1, grp_pi_fu_374_A_ce0, grp_theta_fu_379_A_ce0, grp_chi_fu_384_A_ce0, ap_CS_fsm_state5, ap_CS_fsm_state14, ap_CS_fsm_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_logic_1 = ap_CS_fsm_pp1_stage1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage1_11001)) or ((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)))) then 
            stateAsWords_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            stateAsWords_ce0 <= grp_chi_fu_384_A_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            stateAsWords_ce0 <= grp_theta_fu_379_A_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            stateAsWords_ce0 <= grp_pi_fu_374_A_ce0;
        else 
            stateAsWords_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    stateAsWords_ce1_assign_proc : process(ap_enable_reg_pp1_iter0, ap_CS_fsm_pp1_stage1, ap_block_pp1_stage1_11001, ap_CS_fsm_state17, ap_CS_fsm_pp2_stage0, ap_block_pp2_stage0_11001, ap_enable_reg_pp2_iter0, ap_CS_fsm_state8, grp_pi_fu_374_A_ce1, grp_theta_fu_379_A_ce1, grp_chi_fu_384_A_ce1, ap_CS_fsm_state18, ap_CS_fsm_state14, ap_CS_fsm_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or ((ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0)) or ((ap_const_logic_1 = ap_CS_fsm_pp1_stage1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage1_11001)))) then 
            stateAsWords_ce1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            stateAsWords_ce1 <= grp_chi_fu_384_A_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            stateAsWords_ce1 <= grp_theta_fu_379_A_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            stateAsWords_ce1 <= grp_pi_fu_374_A_ce1;
        else 
            stateAsWords_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    stateAsWords_d0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_pp1_stage0, select_ln353_reg_956, ap_enable_reg_pp1_iter1, grp_pi_fu_374_A_d0, ap_CS_fsm_state5, ap_block_pp1_stage0, ap_CS_fsm_state14, or_ln272_fu_489_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            stateAsWords_d0 <= select_ln353_reg_956;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            stateAsWords_d0 <= or_ln272_fu_489_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            stateAsWords_d0 <= ap_const_lv64_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            stateAsWords_d0 <= grp_pi_fu_374_A_d0;
        else 
            stateAsWords_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    stateAsWords_d1_assign_proc : process(ap_CS_fsm_state8, grp_pi_fu_374_A_d1, grp_theta_fu_379_A_d1, grp_chi_fu_384_A_d1, ap_CS_fsm_state18, ap_CS_fsm_state14, ap_CS_fsm_state16, xor_ln382_fu_680_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            stateAsWords_d1 <= xor_ln382_fu_680_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            stateAsWords_d1 <= grp_chi_fu_384_A_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            stateAsWords_d1 <= grp_theta_fu_379_A_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            stateAsWords_d1 <= grp_pi_fu_374_A_d1;
        else 
            stateAsWords_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    stateAsWords_we0_assign_proc : process(icmp_ln269_fu_412_p2, ap_CS_fsm_state3, icmp_ln352_reg_908, ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter1, grp_pi_fu_374_A_we0, ap_CS_fsm_state5, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln352_reg_908 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln269_fu_412_p2 = ap_const_lv1_0)))) then 
            stateAsWords_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            stateAsWords_we0 <= grp_pi_fu_374_A_we0;
        else 
            stateAsWords_we0 <= ap_const_logic_0;
        end if; 
    end process;


    stateAsWords_we1_assign_proc : process(ap_CS_fsm_state8, grp_pi_fu_374_A_we1, grp_theta_fu_379_A_we1, grp_chi_fu_384_A_we1, ap_CS_fsm_state18, ap_CS_fsm_state14, ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            stateAsWords_we1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            stateAsWords_we1 <= grp_chi_fu_384_A_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            stateAsWords_we1 <= grp_theta_fu_379_A_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            stateAsWords_we1 <= grp_pi_fu_374_A_we1;
        else 
            stateAsWords_we1 <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln353_fu_641_p2 <= std_logic_vector(signed(ap_const_lv7_40) - signed(zext_ln353_4_fu_627_p1));
    trunc_ln272_fu_467_p1 <= j_0_i_reg_251(3 - 1 downto 0);
    trunc_ln282_2_fu_759_p1 <= lshr_ln282_fu_753_p2(8 - 1 downto 0);
    trunc_ln282_fu_732_p1 <= select_ln280_fu_711_p3(3 - 1 downto 0);
    trunc_ln322_fu_784_p1 <= i_0_reg_216(32 - 1 downto 0);
    x_fu_520_p2 <= std_logic_vector(unsigned(ap_phi_mux_x_0_i_phi_fu_290_p4) + unsigned(ap_const_lv3_1));
    xor_ln353_fu_657_p2 <= (shl_ln353_fu_635_p2 xor lshr_ln353_fu_651_p2);
    xor_ln382_fu_680_p2 <= (stateAsWords_q1 xor KeccakRoundConstants_q0);
    y_fu_670_p2 <= std_logic_vector(unsigned(select_ln353_1_reg_927) + unsigned(ap_const_lv3_1));
    zext_ln270_fu_424_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_i_reg_240),64));
    zext_ln271_fu_449_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_0_i_reg_251),8));
    zext_ln272_3_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(instance_state_q0),64));
    zext_ln272_4_fu_479_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln272_9_fu_471_p3),64));
    zext_ln272_fu_458_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln272_fu_453_p2),64));
    zext_ln280_fu_727_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln280_2_fu_719_p3),64));
    zext_ln281_fu_770_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln280_reg_980_pp2_iter1_reg),8));
    zext_ln282_2_fu_779_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln282_fu_773_p2),64));
    zext_ln282_fu_749_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln282_5_fu_742_p3),64));
    zext_ln304_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(dataByteLen_cast_fu_389_p1),33));
    zext_ln322_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(dataByteLen_cast_fu_389_p1),32));
    zext_ln325_1_fu_822_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(partialBlock_21_fu_810_p3),33));
    zext_ln325_fu_818_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(partialBlock_21_fu_810_p3),64));
    zext_ln353_1_fu_587_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln353_4_fu_580_p3),4));
    zext_ln353_2_fu_605_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln353_fu_599_p2),5));
    zext_ln353_3_fu_615_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln353_3_fu_609_p2),64));
    zext_ln353_4_fu_627_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(KeccakRhoOffsets_q0),7));
    zext_ln353_5_fu_631_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(KeccakRhoOffsets_q0),64));
    zext_ln353_6_fu_647_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln353_fu_641_p2),64));
    zext_ln353_fu_566_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln353_3_fu_558_p3),4));
    zext_ln382_fu_675_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(indexRound_assign_reg_263),64));
end behav;
