// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "KeccakWidth1600_Spon_3.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic KeccakWidth1600_Spon_3::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic KeccakWidth1600_Spon_3::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state1 = "1";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state2 = "10";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state3 = "100";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state4 = "1000";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state5 = "10000";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state6 = "100000";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state7 = "1000000";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state8 = "10000000";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state9 = "100000000";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state10 = "1000000000";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state11 = "10000000000";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state12 = "100000000000";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<19> KeccakWidth1600_Spon_3::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> KeccakWidth1600_Spon_3::ap_const_lv1_1 = "1";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_2 = "10";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_A = "1010";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_F = "1111";
const bool KeccakWidth1600_Spon_3::ap_const_boolean_0 = false;
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_10 = "10000";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_11 = "10001";
const sc_lv<1> KeccakWidth1600_Spon_3::ap_const_lv1_0 = "0";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_9 = "1001";
const sc_lv<33> KeccakWidth1600_Spon_3::ap_const_lv33_0 = "000000000000000000000000000000000";
const sc_lv<64> KeccakWidth1600_Spon_3::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_12 = "10010";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_6 = "110";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_C = "1100";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_7 = "111";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_D = "1101";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_8 = "1000";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_E = "1110";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_4 = "100";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_5 = "101";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_B = "1011";
const sc_lv<64> KeccakWidth1600_Spon_3::ap_const_lv64_A7 = "10100111";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_1 = "1";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_3 = "11";
const sc_lv<8> KeccakWidth1600_Spon_3::ap_const_lv8_1 = "1";
const sc_lv<8> KeccakWidth1600_Spon_3::ap_const_lv8_80 = "10000000";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_20 = "100000";
const sc_lv<28> KeccakWidth1600_Spon_3::ap_const_lv28_0 = "0000000000000000000000000000";
const sc_lv<32> KeccakWidth1600_Spon_3::ap_const_lv32_A8 = "10101000";
const sc_lv<6> KeccakWidth1600_Spon_3::ap_const_lv6_20 = "100000";
const bool KeccakWidth1600_Spon_3::ap_const_boolean_1 = true;

KeccakWidth1600_Spon_3::KeccakWidth1600_Spon_3(sc_module_name name) : sc_module(name), mVcdFile(0) {
    stateAsWords_U = new pi_tempA("stateAsWords_U");
    stateAsWords_U->clk(ap_clk);
    stateAsWords_U->reset(ap_rst);
    stateAsWords_U->address0(stateAsWords_address0);
    stateAsWords_U->ce0(stateAsWords_ce0);
    stateAsWords_U->we0(stateAsWords_we0);
    stateAsWords_U->d0(stateAsWords_d0);
    stateAsWords_U->q0(stateAsWords_q0);
    stateAsWords_U->address1(grp_KeccakP1600OnWords_fu_182_state_address1);
    stateAsWords_U->ce1(stateAsWords_ce1);
    stateAsWords_U->we1(stateAsWords_we1);
    stateAsWords_U->d1(grp_KeccakP1600OnWords_fu_182_state_d1);
    stateAsWords_U->q1(stateAsWords_q1);
    stateAsWords_13_U = new pi_tempA("stateAsWords_13_U");
    stateAsWords_13_U->clk(ap_clk);
    stateAsWords_13_U->reset(ap_rst);
    stateAsWords_13_U->address0(stateAsWords_13_address0);
    stateAsWords_13_U->ce0(stateAsWords_13_ce0);
    stateAsWords_13_U->we0(stateAsWords_13_we0);
    stateAsWords_13_U->d0(stateAsWords_13_d0);
    stateAsWords_13_U->q0(stateAsWords_13_q0);
    stateAsWords_13_U->address1(grp_KeccakP1600OnWords_fu_182_state_address1);
    stateAsWords_13_U->ce1(stateAsWords_13_ce1);
    stateAsWords_13_U->we1(stateAsWords_13_we1);
    stateAsWords_13_U->d1(grp_KeccakP1600OnWords_fu_182_state_d1);
    stateAsWords_13_U->q1(stateAsWords_13_q1);
    grp_KeccakP1600OnWords_fu_182 = new KeccakP1600OnWords("grp_KeccakP1600OnWords_fu_182");
    grp_KeccakP1600OnWords_fu_182->ap_clk(ap_clk);
    grp_KeccakP1600OnWords_fu_182->ap_rst(ap_rst);
    grp_KeccakP1600OnWords_fu_182->ap_start(grp_KeccakP1600OnWords_fu_182_ap_start);
    grp_KeccakP1600OnWords_fu_182->ap_done(grp_KeccakP1600OnWords_fu_182_ap_done);
    grp_KeccakP1600OnWords_fu_182->ap_idle(grp_KeccakP1600OnWords_fu_182_ap_idle);
    grp_KeccakP1600OnWords_fu_182->ap_ready(grp_KeccakP1600OnWords_fu_182_ap_ready);
    grp_KeccakP1600OnWords_fu_182->state_address0(grp_KeccakP1600OnWords_fu_182_state_address0);
    grp_KeccakP1600OnWords_fu_182->state_ce0(grp_KeccakP1600OnWords_fu_182_state_ce0);
    grp_KeccakP1600OnWords_fu_182->state_we0(grp_KeccakP1600OnWords_fu_182_state_we0);
    grp_KeccakP1600OnWords_fu_182->state_d0(grp_KeccakP1600OnWords_fu_182_state_d0);
    grp_KeccakP1600OnWords_fu_182->state_q0(grp_KeccakP1600OnWords_fu_182_state_q0);
    grp_KeccakP1600OnWords_fu_182->state_address1(grp_KeccakP1600OnWords_fu_182_state_address1);
    grp_KeccakP1600OnWords_fu_182->state_ce1(grp_KeccakP1600OnWords_fu_182_state_ce1);
    grp_KeccakP1600OnWords_fu_182->state_we1(grp_KeccakP1600OnWords_fu_182_state_we1);
    grp_KeccakP1600OnWords_fu_182->state_d1(grp_KeccakP1600OnWords_fu_182_state_d1);
    grp_KeccakP1600OnWords_fu_182->state_q1(grp_KeccakP1600OnWords_fu_182_state_q1);
    grp_fromWordsToBytes_fu_191 = new fromWordsToBytes("grp_fromWordsToBytes_fu_191");
    grp_fromWordsToBytes_fu_191->ap_clk(ap_clk);
    grp_fromWordsToBytes_fu_191->ap_rst(ap_rst);
    grp_fromWordsToBytes_fu_191->ap_start(grp_fromWordsToBytes_fu_191_ap_start);
    grp_fromWordsToBytes_fu_191->ap_done(grp_fromWordsToBytes_fu_191_ap_done);
    grp_fromWordsToBytes_fu_191->ap_idle(grp_fromWordsToBytes_fu_191_ap_idle);
    grp_fromWordsToBytes_fu_191->ap_ready(grp_fromWordsToBytes_fu_191_ap_ready);
    grp_fromWordsToBytes_fu_191->state_address0(grp_fromWordsToBytes_fu_191_state_address0);
    grp_fromWordsToBytes_fu_191->state_ce0(grp_fromWordsToBytes_fu_191_state_ce0);
    grp_fromWordsToBytes_fu_191->state_we0(grp_fromWordsToBytes_fu_191_state_we0);
    grp_fromWordsToBytes_fu_191->state_d0(grp_fromWordsToBytes_fu_191_state_d0);
    grp_fromWordsToBytes_fu_191->stateAsWords_address0(grp_fromWordsToBytes_fu_191_stateAsWords_address0);
    grp_fromWordsToBytes_fu_191->stateAsWords_ce0(grp_fromWordsToBytes_fu_191_stateAsWords_ce0);
    grp_fromWordsToBytes_fu_191->stateAsWords_q0(grp_fromWordsToBytes_fu_191_stateAsWords_q0);
    grp_fromBytesToWords_fu_198 = new fromBytesToWords("grp_fromBytesToWords_fu_198");
    grp_fromBytesToWords_fu_198->ap_clk(ap_clk);
    grp_fromBytesToWords_fu_198->ap_rst(ap_rst);
    grp_fromBytesToWords_fu_198->ap_start(grp_fromBytesToWords_fu_198_ap_start);
    grp_fromBytesToWords_fu_198->ap_done(grp_fromBytesToWords_fu_198_ap_done);
    grp_fromBytesToWords_fu_198->ap_idle(grp_fromBytesToWords_fu_198_ap_idle);
    grp_fromBytesToWords_fu_198->ap_ready(grp_fromBytesToWords_fu_198_ap_ready);
    grp_fromBytesToWords_fu_198->stateAsWords_address0(grp_fromBytesToWords_fu_198_stateAsWords_address0);
    grp_fromBytesToWords_fu_198->stateAsWords_ce0(grp_fromBytesToWords_fu_198_stateAsWords_ce0);
    grp_fromBytesToWords_fu_198->stateAsWords_we0(grp_fromBytesToWords_fu_198_stateAsWords_we0);
    grp_fromBytesToWords_fu_198->stateAsWords_d0(grp_fromBytesToWords_fu_198_stateAsWords_d0);
    grp_fromBytesToWords_fu_198->stateAsWords_q0(grp_fromBytesToWords_fu_198_stateAsWords_q0);
    grp_fromBytesToWords_fu_198->state_address0(grp_fromBytesToWords_fu_198_state_address0);
    grp_fromBytesToWords_fu_198->state_ce0(grp_fromBytesToWords_fu_198_state_ce0);
    grp_fromBytesToWords_fu_198->state_q0(instance_state_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln323_fu_265_p2);
    sensitive << ( offset_assign_reg_158 );
    sensitive << ( zext_ln322_fu_262_p1 );

    SC_METHOD(thread_add_ln331_fu_346_p2);
    sensitive << ( zext_ln325_reg_392 );
    sensitive << ( curData_0_idx_reg_146 );

    SC_METHOD(thread_add_ln332_fu_341_p2);
    sensitive << ( partialBlock_25_reg_386 );
    sensitive << ( offset_assign_reg_158 );

    SC_METHOD(thread_add_ln394_2_fu_335_p2);
    sensitive << ( trunc_ln304_fu_331_p1 );
    sensitive << ( trunc_ln394_fu_327_p1 );

    SC_METHOD(thread_add_ln394_fu_316_p2);
    sensitive << ( offset_assign_reg_158 );
    sensitive << ( loop_0_i1_reg_171 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state10_on_subcall_done);
    sensitive << ( icmp_ln299_reg_360 );
    sensitive << ( grp_fromWordsToBytes_fu_191_ap_done );

    SC_METHOD(thread_ap_block_state16_on_subcall_done);
    sensitive << ( icmp_ln305_reg_377 );
    sensitive << ( grp_fromWordsToBytes_fu_191_ap_done );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln304_fu_240_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_instance_byteIOIndex_2_phi_fu_115_p4);
    sensitive << ( icmp_ln299_reg_360 );
    sensitive << ( instance_byteIOIndex_2_reg_112 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln304_fu_240_p2 );

    SC_METHOD(thread_data_0_address0);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( zext_ln394_2_fu_351_p1 );

    SC_METHOD(thread_data_0_ce0);
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_data_0_d0);
    sensitive << ( instance_state_q0 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_data_0_we0);
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_grp_KeccakP1600OnWords_fu_182_ap_start);
    sensitive << ( grp_KeccakP1600OnWords_fu_182_ap_start_reg );

    SC_METHOD(thread_grp_KeccakP1600OnWords_fu_182_state_q0);
    sensitive << ( stateAsWords_q0 );
    sensitive << ( stateAsWords_13_q0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_grp_KeccakP1600OnWords_fu_182_state_q1);
    sensitive << ( stateAsWords_q1 );
    sensitive << ( stateAsWords_13_q1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_grp_fromBytesToWords_fu_198_ap_start);
    sensitive << ( grp_fromBytesToWords_fu_198_ap_start_reg );

    SC_METHOD(thread_grp_fromBytesToWords_fu_198_stateAsWords_q0);
    sensitive << ( stateAsWords_q0 );
    sensitive << ( stateAsWords_13_q0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_grp_fromWordsToBytes_fu_191_ap_start);
    sensitive << ( grp_fromWordsToBytes_fu_191_ap_start_reg );

    SC_METHOD(thread_grp_fromWordsToBytes_fu_191_stateAsWords_q0);
    sensitive << ( icmp_ln299_reg_360 );
    sensitive << ( icmp_ln305_reg_377 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( stateAsWords_q0 );
    sensitive << ( stateAsWords_13_q0 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_i_fu_299_p2);
    sensitive << ( i_0_reg_134 );
    sensitive << ( zext_ln325_3_fu_295_p1 );

    SC_METHOD(thread_icmp_ln299_fu_205_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( instance_squeezing_read );

    SC_METHOD(thread_icmp_ln304_fu_240_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( tmp_fu_230_p4 );

    SC_METHOD(thread_icmp_ln305_fu_246_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln304_fu_240_p2 );
    sensitive << ( instance_byteIOIndex_1_reg_123 );

    SC_METHOD(thread_icmp_ln323_fu_271_p2);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( add_ln323_fu_265_p2 );

    SC_METHOD(thread_icmp_ln393_fu_305_p2);
    sensitive << ( partialBlock_25_reg_386 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( loop_0_i1_reg_171 );

    SC_METHOD(thread_instance_state_addr_1_reg_369);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_instance_state_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln299_reg_360 );
    sensitive << ( instance_state_addr_reg_364 );
    sensitive << ( instance_state_addr_1_reg_369 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln305_reg_377 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( grp_fromWordsToBytes_fu_191_state_address0 );
    sensitive << ( grp_fromBytesToWords_fu_198_state_address0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( zext_ln149_fu_211_p1 );
    sensitive << ( zext_ln394_fu_322_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_instance_state_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln299_reg_360 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln305_reg_377 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( grp_fromWordsToBytes_fu_191_state_ce0 );
    sensitive << ( grp_fromBytesToWords_fu_198_state_ce0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_instance_state_d0);
    sensitive << ( icmp_ln299_reg_360 );
    sensitive << ( icmp_ln305_reg_377 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( grp_fromWordsToBytes_fu_191_state_d0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( xor_ln149_fu_216_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( xor_ln149_16_fu_223_p2 );

    SC_METHOD(thread_instance_state_we0);
    sensitive << ( icmp_ln299_reg_360 );
    sensitive << ( icmp_ln305_reg_377 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( grp_fromWordsToBytes_fu_191_state_we0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_loop_fu_310_p2);
    sensitive << ( loop_0_i1_reg_171 );

    SC_METHOD(thread_partialBlock_24_fu_277_p2);
    sensitive << ( offset_assign_reg_158 );

    SC_METHOD(thread_partialBlock_25_fu_283_p3);
    sensitive << ( zext_ln322_fu_262_p1 );
    sensitive << ( icmp_ln323_fu_271_p2 );
    sensitive << ( partialBlock_24_fu_277_p2 );

    SC_METHOD(thread_partialBlock_fu_256_p2);
    sensitive << ( trunc_ln322_fu_252_p1 );

    SC_METHOD(thread_stateAsWords_13_address0);
    sensitive << ( icmp_ln305_reg_377 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( grp_KeccakP1600OnWords_fu_182_state_address0 );
    sensitive << ( grp_fromWordsToBytes_fu_191_stateAsWords_address0 );
    sensitive << ( grp_fromBytesToWords_fu_198_stateAsWords_address0 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_stateAsWords_13_ce0);
    sensitive << ( icmp_ln305_reg_377 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( grp_KeccakP1600OnWords_fu_182_state_ce0 );
    sensitive << ( grp_fromWordsToBytes_fu_191_stateAsWords_ce0 );
    sensitive << ( grp_fromBytesToWords_fu_198_stateAsWords_ce0 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_stateAsWords_13_ce1);
    sensitive << ( grp_KeccakP1600OnWords_fu_182_state_ce1 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_stateAsWords_13_d0);
    sensitive << ( grp_KeccakP1600OnWords_fu_182_state_d0 );
    sensitive << ( grp_fromBytesToWords_fu_198_stateAsWords_d0 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_stateAsWords_13_we0);
    sensitive << ( grp_KeccakP1600OnWords_fu_182_state_we0 );
    sensitive << ( grp_fromBytesToWords_fu_198_stateAsWords_we0 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_stateAsWords_13_we1);
    sensitive << ( grp_KeccakP1600OnWords_fu_182_state_we1 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_stateAsWords_address0);
    sensitive << ( icmp_ln299_reg_360 );
    sensitive << ( grp_KeccakP1600OnWords_fu_182_state_address0 );
    sensitive << ( grp_fromWordsToBytes_fu_191_stateAsWords_address0 );
    sensitive << ( grp_fromBytesToWords_fu_198_stateAsWords_address0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_stateAsWords_ce0);
    sensitive << ( icmp_ln299_reg_360 );
    sensitive << ( grp_KeccakP1600OnWords_fu_182_state_ce0 );
    sensitive << ( grp_fromWordsToBytes_fu_191_stateAsWords_ce0 );
    sensitive << ( grp_fromBytesToWords_fu_198_stateAsWords_ce0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_stateAsWords_ce1);
    sensitive << ( grp_KeccakP1600OnWords_fu_182_state_ce1 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_stateAsWords_d0);
    sensitive << ( grp_KeccakP1600OnWords_fu_182_state_d0 );
    sensitive << ( grp_fromBytesToWords_fu_198_stateAsWords_d0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_stateAsWords_we0);
    sensitive << ( grp_KeccakP1600OnWords_fu_182_state_we0 );
    sensitive << ( grp_fromBytesToWords_fu_198_stateAsWords_we0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_stateAsWords_we1);
    sensitive << ( grp_KeccakP1600OnWords_fu_182_state_we1 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_tmp_fu_230_p4);
    sensitive << ( i_0_reg_134 );

    SC_METHOD(thread_trunc_ln304_fu_331_p1);
    sensitive << ( curData_0_idx_reg_146 );

    SC_METHOD(thread_trunc_ln322_fu_252_p1);
    sensitive << ( i_0_reg_134 );

    SC_METHOD(thread_trunc_ln394_fu_327_p1);
    sensitive << ( loop_0_i1_reg_171 );

    SC_METHOD(thread_xor_ln149_16_fu_223_p2);
    sensitive << ( instance_state_q0 );

    SC_METHOD(thread_xor_ln149_fu_216_p2);
    sensitive << ( instance_state_q0 );

    SC_METHOD(thread_zext_ln149_fu_211_p1);
    sensitive << ( instance_byteIOIndex_read );

    SC_METHOD(thread_zext_ln322_fu_262_p1);
    sensitive << ( partialBlock_reg_381 );

    SC_METHOD(thread_zext_ln325_3_fu_295_p1);
    sensitive << ( partialBlock_25_fu_283_p3 );

    SC_METHOD(thread_zext_ln325_fu_291_p1);
    sensitive << ( partialBlock_25_fu_283_p3 );

    SC_METHOD(thread_zext_ln394_2_fu_351_p1);
    sensitive << ( add_ln394_2_reg_415 );

    SC_METHOD(thread_zext_ln394_fu_322_p1);
    sensitive << ( add_ln394_fu_316_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln299_fu_205_p2 );
    sensitive << ( icmp_ln305_fu_246_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln304_fu_240_p2 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_block_state16_on_subcall_done );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( icmp_ln393_fu_305_p2 );
    sensitive << ( grp_KeccakP1600OnWords_fu_182_ap_done );
    sensitive << ( grp_fromBytesToWords_fu_198_ap_done );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_block_state10_on_subcall_done );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state12 );

    ap_CS_fsm = "0000000000000000001";
    grp_KeccakP1600OnWords_fu_182_ap_start_reg = SC_LOGIC_0;
    grp_fromWordsToBytes_fu_191_ap_start_reg = SC_LOGIC_0;
    grp_fromBytesToWords_fu_198_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "KeccakWidth1600_Spon_3_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, instance_state_address0, "(port)instance_state_address0");
    sc_trace(mVcdFile, instance_state_ce0, "(port)instance_state_ce0");
    sc_trace(mVcdFile, instance_state_we0, "(port)instance_state_we0");
    sc_trace(mVcdFile, instance_state_d0, "(port)instance_state_d0");
    sc_trace(mVcdFile, instance_state_q0, "(port)instance_state_q0");
    sc_trace(mVcdFile, instance_byteIOIndex_read, "(port)instance_byteIOIndex_read");
    sc_trace(mVcdFile, instance_squeezing_read, "(port)instance_squeezing_read");
    sc_trace(mVcdFile, data_0_address0, "(port)data_0_address0");
    sc_trace(mVcdFile, data_0_ce0, "(port)data_0_ce0");
    sc_trace(mVcdFile, data_0_we0, "(port)data_0_we0");
    sc_trace(mVcdFile, data_0_d0, "(port)data_0_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, icmp_ln299_fu_205_p2, "icmp_ln299_fu_205_p2");
    sc_trace(mVcdFile, icmp_ln299_reg_360, "icmp_ln299_reg_360");
    sc_trace(mVcdFile, instance_state_addr_reg_364, "instance_state_addr_reg_364");
    sc_trace(mVcdFile, instance_state_addr_1_reg_369, "instance_state_addr_1_reg_369");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln305_fu_246_p2, "icmp_ln305_fu_246_p2");
    sc_trace(mVcdFile, icmp_ln305_reg_377, "icmp_ln305_reg_377");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, icmp_ln304_fu_240_p2, "icmp_ln304_fu_240_p2");
    sc_trace(mVcdFile, partialBlock_fu_256_p2, "partialBlock_fu_256_p2");
    sc_trace(mVcdFile, partialBlock_reg_381, "partialBlock_reg_381");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, grp_fromWordsToBytes_fu_191_ap_ready, "grp_fromWordsToBytes_fu_191_ap_ready");
    sc_trace(mVcdFile, grp_fromWordsToBytes_fu_191_ap_done, "grp_fromWordsToBytes_fu_191_ap_done");
    sc_trace(mVcdFile, ap_block_state16_on_subcall_done, "ap_block_state16_on_subcall_done");
    sc_trace(mVcdFile, partialBlock_25_fu_283_p3, "partialBlock_25_fu_283_p3");
    sc_trace(mVcdFile, partialBlock_25_reg_386, "partialBlock_25_reg_386");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, zext_ln325_fu_291_p1, "zext_ln325_fu_291_p1");
    sc_trace(mVcdFile, zext_ln325_reg_392, "zext_ln325_reg_392");
    sc_trace(mVcdFile, i_fu_299_p2, "i_fu_299_p2");
    sc_trace(mVcdFile, i_reg_397, "i_reg_397");
    sc_trace(mVcdFile, loop_fu_310_p2, "loop_fu_310_p2");
    sc_trace(mVcdFile, loop_reg_405, "loop_reg_405");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, icmp_ln393_fu_305_p2, "icmp_ln393_fu_305_p2");
    sc_trace(mVcdFile, add_ln394_2_fu_335_p2, "add_ln394_2_fu_335_p2");
    sc_trace(mVcdFile, add_ln394_2_reg_415, "add_ln394_2_reg_415");
    sc_trace(mVcdFile, add_ln332_fu_341_p2, "add_ln332_fu_341_p2");
    sc_trace(mVcdFile, add_ln331_fu_346_p2, "add_ln331_fu_346_p2");
    sc_trace(mVcdFile, stateAsWords_address0, "stateAsWords_address0");
    sc_trace(mVcdFile, stateAsWords_ce0, "stateAsWords_ce0");
    sc_trace(mVcdFile, stateAsWords_we0, "stateAsWords_we0");
    sc_trace(mVcdFile, stateAsWords_d0, "stateAsWords_d0");
    sc_trace(mVcdFile, stateAsWords_q0, "stateAsWords_q0");
    sc_trace(mVcdFile, stateAsWords_ce1, "stateAsWords_ce1");
    sc_trace(mVcdFile, stateAsWords_we1, "stateAsWords_we1");
    sc_trace(mVcdFile, stateAsWords_q1, "stateAsWords_q1");
    sc_trace(mVcdFile, stateAsWords_13_address0, "stateAsWords_13_address0");
    sc_trace(mVcdFile, stateAsWords_13_ce0, "stateAsWords_13_ce0");
    sc_trace(mVcdFile, stateAsWords_13_we0, "stateAsWords_13_we0");
    sc_trace(mVcdFile, stateAsWords_13_d0, "stateAsWords_13_d0");
    sc_trace(mVcdFile, stateAsWords_13_q0, "stateAsWords_13_q0");
    sc_trace(mVcdFile, stateAsWords_13_ce1, "stateAsWords_13_ce1");
    sc_trace(mVcdFile, stateAsWords_13_we1, "stateAsWords_13_we1");
    sc_trace(mVcdFile, stateAsWords_13_q1, "stateAsWords_13_q1");
    sc_trace(mVcdFile, grp_KeccakP1600OnWords_fu_182_ap_start, "grp_KeccakP1600OnWords_fu_182_ap_start");
    sc_trace(mVcdFile, grp_KeccakP1600OnWords_fu_182_ap_done, "grp_KeccakP1600OnWords_fu_182_ap_done");
    sc_trace(mVcdFile, grp_KeccakP1600OnWords_fu_182_ap_idle, "grp_KeccakP1600OnWords_fu_182_ap_idle");
    sc_trace(mVcdFile, grp_KeccakP1600OnWords_fu_182_ap_ready, "grp_KeccakP1600OnWords_fu_182_ap_ready");
    sc_trace(mVcdFile, grp_KeccakP1600OnWords_fu_182_state_address0, "grp_KeccakP1600OnWords_fu_182_state_address0");
    sc_trace(mVcdFile, grp_KeccakP1600OnWords_fu_182_state_ce0, "grp_KeccakP1600OnWords_fu_182_state_ce0");
    sc_trace(mVcdFile, grp_KeccakP1600OnWords_fu_182_state_we0, "grp_KeccakP1600OnWords_fu_182_state_we0");
    sc_trace(mVcdFile, grp_KeccakP1600OnWords_fu_182_state_d0, "grp_KeccakP1600OnWords_fu_182_state_d0");
    sc_trace(mVcdFile, grp_KeccakP1600OnWords_fu_182_state_q0, "grp_KeccakP1600OnWords_fu_182_state_q0");
    sc_trace(mVcdFile, grp_KeccakP1600OnWords_fu_182_state_address1, "grp_KeccakP1600OnWords_fu_182_state_address1");
    sc_trace(mVcdFile, grp_KeccakP1600OnWords_fu_182_state_ce1, "grp_KeccakP1600OnWords_fu_182_state_ce1");
    sc_trace(mVcdFile, grp_KeccakP1600OnWords_fu_182_state_we1, "grp_KeccakP1600OnWords_fu_182_state_we1");
    sc_trace(mVcdFile, grp_KeccakP1600OnWords_fu_182_state_d1, "grp_KeccakP1600OnWords_fu_182_state_d1");
    sc_trace(mVcdFile, grp_KeccakP1600OnWords_fu_182_state_q1, "grp_KeccakP1600OnWords_fu_182_state_q1");
    sc_trace(mVcdFile, grp_fromWordsToBytes_fu_191_ap_start, "grp_fromWordsToBytes_fu_191_ap_start");
    sc_trace(mVcdFile, grp_fromWordsToBytes_fu_191_ap_idle, "grp_fromWordsToBytes_fu_191_ap_idle");
    sc_trace(mVcdFile, grp_fromWordsToBytes_fu_191_state_address0, "grp_fromWordsToBytes_fu_191_state_address0");
    sc_trace(mVcdFile, grp_fromWordsToBytes_fu_191_state_ce0, "grp_fromWordsToBytes_fu_191_state_ce0");
    sc_trace(mVcdFile, grp_fromWordsToBytes_fu_191_state_we0, "grp_fromWordsToBytes_fu_191_state_we0");
    sc_trace(mVcdFile, grp_fromWordsToBytes_fu_191_state_d0, "grp_fromWordsToBytes_fu_191_state_d0");
    sc_trace(mVcdFile, grp_fromWordsToBytes_fu_191_stateAsWords_address0, "grp_fromWordsToBytes_fu_191_stateAsWords_address0");
    sc_trace(mVcdFile, grp_fromWordsToBytes_fu_191_stateAsWords_ce0, "grp_fromWordsToBytes_fu_191_stateAsWords_ce0");
    sc_trace(mVcdFile, grp_fromWordsToBytes_fu_191_stateAsWords_q0, "grp_fromWordsToBytes_fu_191_stateAsWords_q0");
    sc_trace(mVcdFile, grp_fromBytesToWords_fu_198_ap_start, "grp_fromBytesToWords_fu_198_ap_start");
    sc_trace(mVcdFile, grp_fromBytesToWords_fu_198_ap_done, "grp_fromBytesToWords_fu_198_ap_done");
    sc_trace(mVcdFile, grp_fromBytesToWords_fu_198_ap_idle, "grp_fromBytesToWords_fu_198_ap_idle");
    sc_trace(mVcdFile, grp_fromBytesToWords_fu_198_ap_ready, "grp_fromBytesToWords_fu_198_ap_ready");
    sc_trace(mVcdFile, grp_fromBytesToWords_fu_198_stateAsWords_address0, "grp_fromBytesToWords_fu_198_stateAsWords_address0");
    sc_trace(mVcdFile, grp_fromBytesToWords_fu_198_stateAsWords_ce0, "grp_fromBytesToWords_fu_198_stateAsWords_ce0");
    sc_trace(mVcdFile, grp_fromBytesToWords_fu_198_stateAsWords_we0, "grp_fromBytesToWords_fu_198_stateAsWords_we0");
    sc_trace(mVcdFile, grp_fromBytesToWords_fu_198_stateAsWords_d0, "grp_fromBytesToWords_fu_198_stateAsWords_d0");
    sc_trace(mVcdFile, grp_fromBytesToWords_fu_198_stateAsWords_q0, "grp_fromBytesToWords_fu_198_stateAsWords_q0");
    sc_trace(mVcdFile, grp_fromBytesToWords_fu_198_state_address0, "grp_fromBytesToWords_fu_198_state_address0");
    sc_trace(mVcdFile, grp_fromBytesToWords_fu_198_state_ce0, "grp_fromBytesToWords_fu_198_state_ce0");
    sc_trace(mVcdFile, ap_phi_mux_instance_byteIOIndex_2_phi_fu_115_p4, "ap_phi_mux_instance_byteIOIndex_2_phi_fu_115_p4");
    sc_trace(mVcdFile, instance_byteIOIndex_2_reg_112, "instance_byteIOIndex_2_reg_112");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_block_state10_on_subcall_done, "ap_block_state10_on_subcall_done");
    sc_trace(mVcdFile, instance_byteIOIndex_1_reg_123, "instance_byteIOIndex_1_reg_123");
    sc_trace(mVcdFile, i_0_reg_134, "i_0_reg_134");
    sc_trace(mVcdFile, curData_0_idx_reg_146, "curData_0_idx_reg_146");
    sc_trace(mVcdFile, offset_assign_reg_158, "offset_assign_reg_158");
    sc_trace(mVcdFile, loop_0_i1_reg_171, "loop_0_i1_reg_171");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, grp_KeccakP1600OnWords_fu_182_ap_start_reg, "grp_KeccakP1600OnWords_fu_182_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, grp_fromWordsToBytes_fu_191_ap_start_reg, "grp_fromWordsToBytes_fu_191_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, grp_fromBytesToWords_fu_198_ap_start_reg, "grp_fromBytesToWords_fu_198_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, zext_ln149_fu_211_p1, "zext_ln149_fu_211_p1");
    sc_trace(mVcdFile, zext_ln394_fu_322_p1, "zext_ln394_fu_322_p1");
    sc_trace(mVcdFile, zext_ln394_2_fu_351_p1, "zext_ln394_2_fu_351_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, xor_ln149_fu_216_p2, "xor_ln149_fu_216_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, xor_ln149_16_fu_223_p2, "xor_ln149_16_fu_223_p2");
    sc_trace(mVcdFile, tmp_fu_230_p4, "tmp_fu_230_p4");
    sc_trace(mVcdFile, trunc_ln322_fu_252_p1, "trunc_ln322_fu_252_p1");
    sc_trace(mVcdFile, zext_ln322_fu_262_p1, "zext_ln322_fu_262_p1");
    sc_trace(mVcdFile, add_ln323_fu_265_p2, "add_ln323_fu_265_p2");
    sc_trace(mVcdFile, icmp_ln323_fu_271_p2, "icmp_ln323_fu_271_p2");
    sc_trace(mVcdFile, partialBlock_24_fu_277_p2, "partialBlock_24_fu_277_p2");
    sc_trace(mVcdFile, zext_ln325_3_fu_295_p1, "zext_ln325_3_fu_295_p1");
    sc_trace(mVcdFile, add_ln394_fu_316_p2, "add_ln394_fu_316_p2");
    sc_trace(mVcdFile, trunc_ln304_fu_331_p1, "trunc_ln304_fu_331_p1");
    sc_trace(mVcdFile, trunc_ln394_fu_327_p1, "trunc_ln394_fu_327_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

KeccakWidth1600_Spon_3::~KeccakWidth1600_Spon_3() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete stateAsWords_U;
    delete stateAsWords_13_U;
    delete grp_KeccakP1600OnWords_fu_182;
    delete grp_fromWordsToBytes_fu_191;
    delete grp_fromBytesToWords_fu_198;
}

void KeccakWidth1600_Spon_3::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(ap_block_state10_on_subcall_done.read(), ap_const_boolean_0))) {
        curData_0_idx_reg_146 = ap_const_lv64_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln393_fu_305_p2.read()))) {
        curData_0_idx_reg_146 = add_ln331_fu_346_p2.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_KeccakP1600OnWords_fu_182_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
            grp_KeccakP1600OnWords_fu_182_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_KeccakP1600OnWords_fu_182_ap_ready.read())) {
            grp_KeccakP1600OnWords_fu_182_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_fromBytesToWords_fu_198_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln304_fu_240_p2.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln305_fu_246_p2.read())))) {
            grp_fromBytesToWords_fu_198_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_fromBytesToWords_fu_198_ap_ready.read())) {
            grp_fromBytesToWords_fu_198_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_fromWordsToBytes_fu_191_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
            grp_fromWordsToBytes_fu_191_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_fromWordsToBytes_fu_191_ap_ready.read())) {
            grp_fromWordsToBytes_fu_191_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(ap_block_state10_on_subcall_done.read(), ap_const_boolean_0))) {
        i_0_reg_134 = ap_const_lv33_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln393_fu_305_p2.read()))) {
        i_0_reg_134 = i_reg_397.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(ap_block_state10_on_subcall_done.read(), ap_const_boolean_0))) {
        instance_byteIOIndex_1_reg_123 = ap_phi_mux_instance_byteIOIndex_2_phi_fu_115_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln393_fu_305_p2.read()))) {
        instance_byteIOIndex_1_reg_123 = add_ln332_fu_341_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(icmp_ln299_reg_360.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_state10_on_subcall_done.read(), ap_const_boolean_0))) {
        instance_byteIOIndex_2_reg_112 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(icmp_ln299_fu_205_p2.read(), ap_const_lv1_0))) {
        instance_byteIOIndex_2_reg_112 = instance_byteIOIndex_read.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        loop_0_i1_reg_171 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        loop_0_i1_reg_171 = loop_reg_405.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln304_fu_240_p2.read()) && 
         esl_seteq<1,1,1>(icmp_ln305_fu_246_p2.read(), ap_const_lv1_0))) {
        offset_assign_reg_158 = instance_byteIOIndex_1_reg_123.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln305_reg_377.read()) && 
                esl_seteq<1,1,1>(ap_block_state16_on_subcall_done.read(), ap_const_boolean_0))) {
        offset_assign_reg_158 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && esl_seteq<1,1,1>(icmp_ln393_fu_305_p2.read(), ap_const_lv1_0))) {
        add_ln394_2_reg_415 = add_ln394_2_fu_335_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        i_reg_397 = i_fu_299_p2.read();
        partialBlock_25_reg_386 = partialBlock_25_fu_283_p3.read();
        zext_ln325_reg_392 = zext_ln325_fu_291_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        icmp_ln299_reg_360 = icmp_ln299_fu_205_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln304_fu_240_p2.read()))) {
        icmp_ln305_reg_377 = icmp_ln305_fu_246_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(icmp_ln299_fu_205_p2.read(), ap_const_lv1_1))) {
        instance_state_addr_reg_364 =  (sc_lv<8>) (zext_ln149_fu_211_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        loop_reg_405 = loop_fu_310_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(ap_block_state16_on_subcall_done.read(), ap_const_boolean_0))) {
        partialBlock_reg_381 = partialBlock_fu_256_p2.read();
    }
}

void KeccakWidth1600_Spon_3::thread_add_ln323_fu_265_p2() {
    add_ln323_fu_265_p2 = (!offset_assign_reg_158.read().is_01() || !zext_ln322_fu_262_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(offset_assign_reg_158.read()) + sc_biguint<32>(zext_ln322_fu_262_p1.read()));
}

void KeccakWidth1600_Spon_3::thread_add_ln331_fu_346_p2() {
    add_ln331_fu_346_p2 = (!zext_ln325_reg_392.read().is_01() || !curData_0_idx_reg_146.read().is_01())? sc_lv<64>(): (sc_biguint<64>(zext_ln325_reg_392.read()) + sc_biguint<64>(curData_0_idx_reg_146.read()));
}

void KeccakWidth1600_Spon_3::thread_add_ln332_fu_341_p2() {
    add_ln332_fu_341_p2 = (!offset_assign_reg_158.read().is_01() || !partialBlock_25_reg_386.read().is_01())? sc_lv<32>(): (sc_biguint<32>(offset_assign_reg_158.read()) + sc_biguint<32>(partialBlock_25_reg_386.read()));
}

void KeccakWidth1600_Spon_3::thread_add_ln394_2_fu_335_p2() {
    add_ln394_2_fu_335_p2 = (!trunc_ln304_fu_331_p1.read().is_01() || !trunc_ln394_fu_327_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(trunc_ln304_fu_331_p1.read()) + sc_biguint<7>(trunc_ln394_fu_327_p1.read()));
}

void KeccakWidth1600_Spon_3::thread_add_ln394_fu_316_p2() {
    add_ln394_fu_316_p2 = (!loop_0_i1_reg_171.read().is_01() || !offset_assign_reg_158.read().is_01())? sc_lv<32>(): (sc_biguint<32>(loop_0_i1_reg_171.read()) + sc_biguint<32>(offset_assign_reg_158.read()));
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void KeccakWidth1600_Spon_3::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void KeccakWidth1600_Spon_3::thread_ap_block_state10_on_subcall_done() {
    ap_block_state10_on_subcall_done = (esl_seteq<1,1,1>(ap_const_logic_0, grp_fromWordsToBytes_fu_191_ap_done.read()) && esl_seteq<1,1,1>(icmp_ln299_reg_360.read(), ap_const_lv1_1));
}

void KeccakWidth1600_Spon_3::thread_ap_block_state16_on_subcall_done() {
    ap_block_state16_on_subcall_done = (esl_seteq<1,1,1>(ap_const_logic_0, grp_fromWordsToBytes_fu_191_ap_done.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln305_reg_377.read()));
}

void KeccakWidth1600_Spon_3::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(icmp_ln304_fu_240_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_3::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_3::thread_ap_phi_mux_instance_byteIOIndex_2_phi_fu_115_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(icmp_ln299_reg_360.read(), ap_const_lv1_1))) {
        ap_phi_mux_instance_byteIOIndex_2_phi_fu_115_p4 = ap_const_lv32_0;
    } else {
        ap_phi_mux_instance_byteIOIndex_2_phi_fu_115_p4 = instance_byteIOIndex_2_reg_112.read();
    }
}

void KeccakWidth1600_Spon_3::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(icmp_ln304_fu_240_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_3::thread_data_0_address0() {
    data_0_address0 =  (sc_lv<5>) (zext_ln394_2_fu_351_p1.read());
}

void KeccakWidth1600_Spon_3::thread_data_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        data_0_ce0 = ap_const_logic_1;
    } else {
        data_0_ce0 = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_3::thread_data_0_d0() {
    data_0_d0 = instance_state_q0.read();
}

void KeccakWidth1600_Spon_3::thread_data_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        data_0_we0 = ap_const_logic_1;
    } else {
        data_0_we0 = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_3::thread_grp_KeccakP1600OnWords_fu_182_ap_start() {
    grp_KeccakP1600OnWords_fu_182_ap_start = grp_KeccakP1600OnWords_fu_182_ap_start_reg.read();
}

void KeccakWidth1600_Spon_3::thread_grp_KeccakP1600OnWords_fu_182_state_q0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        grp_KeccakP1600OnWords_fu_182_state_q0 = stateAsWords_13_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        grp_KeccakP1600OnWords_fu_182_state_q0 = stateAsWords_q0.read();
    } else {
        grp_KeccakP1600OnWords_fu_182_state_q0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void KeccakWidth1600_Spon_3::thread_grp_KeccakP1600OnWords_fu_182_state_q1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        grp_KeccakP1600OnWords_fu_182_state_q1 = stateAsWords_13_q1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        grp_KeccakP1600OnWords_fu_182_state_q1 = stateAsWords_q1.read();
    } else {
        grp_KeccakP1600OnWords_fu_182_state_q1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void KeccakWidth1600_Spon_3::thread_grp_fromBytesToWords_fu_198_ap_start() {
    grp_fromBytesToWords_fu_198_ap_start = grp_fromBytesToWords_fu_198_ap_start_reg.read();
}

void KeccakWidth1600_Spon_3::thread_grp_fromBytesToWords_fu_198_stateAsWords_q0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        grp_fromBytesToWords_fu_198_stateAsWords_q0 = stateAsWords_13_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fromBytesToWords_fu_198_stateAsWords_q0 = stateAsWords_q0.read();
    } else {
        grp_fromBytesToWords_fu_198_stateAsWords_q0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void KeccakWidth1600_Spon_3::thread_grp_fromWordsToBytes_fu_191_ap_start() {
    grp_fromWordsToBytes_fu_191_ap_start = grp_fromWordsToBytes_fu_191_ap_start_reg.read();
}

void KeccakWidth1600_Spon_3::thread_grp_fromWordsToBytes_fu_191_stateAsWords_q0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln305_reg_377.read()))) {
        grp_fromWordsToBytes_fu_191_stateAsWords_q0 = stateAsWords_13_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(icmp_ln299_reg_360.read(), ap_const_lv1_1))) {
        grp_fromWordsToBytes_fu_191_stateAsWords_q0 = stateAsWords_q0.read();
    } else {
        grp_fromWordsToBytes_fu_191_stateAsWords_q0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void KeccakWidth1600_Spon_3::thread_i_fu_299_p2() {
    i_fu_299_p2 = (!zext_ln325_3_fu_295_p1.read().is_01() || !i_0_reg_134.read().is_01())? sc_lv<33>(): (sc_biguint<33>(zext_ln325_3_fu_295_p1.read()) + sc_biguint<33>(i_0_reg_134.read()));
}

void KeccakWidth1600_Spon_3::thread_icmp_ln299_fu_205_p2() {
    icmp_ln299_fu_205_p2 = (!instance_squeezing_read.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(instance_squeezing_read.read() == ap_const_lv32_0);
}

void KeccakWidth1600_Spon_3::thread_icmp_ln304_fu_240_p2() {
    icmp_ln304_fu_240_p2 = (!tmp_fu_230_p4.read().is_01() || !ap_const_lv28_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_230_p4.read() == ap_const_lv28_0);
}

void KeccakWidth1600_Spon_3::thread_icmp_ln305_fu_246_p2() {
    icmp_ln305_fu_246_p2 = (!instance_byteIOIndex_1_reg_123.read().is_01() || !ap_const_lv32_A8.is_01())? sc_lv<1>(): sc_lv<1>(instance_byteIOIndex_1_reg_123.read() == ap_const_lv32_A8);
}

void KeccakWidth1600_Spon_3::thread_icmp_ln323_fu_271_p2() {
    icmp_ln323_fu_271_p2 = (!add_ln323_fu_265_p2.read().is_01() || !ap_const_lv32_A8.is_01())? sc_lv<1>(): (sc_biguint<32>(add_ln323_fu_265_p2.read()) > sc_biguint<32>(ap_const_lv32_A8));
}

void KeccakWidth1600_Spon_3::thread_icmp_ln393_fu_305_p2() {
    icmp_ln393_fu_305_p2 = (!loop_0_i1_reg_171.read().is_01() || !partialBlock_25_reg_386.read().is_01())? sc_lv<1>(): sc_lv<1>(loop_0_i1_reg_171.read() == partialBlock_25_reg_386.read());
}

void KeccakWidth1600_Spon_3::thread_instance_state_addr_1_reg_369() {
    instance_state_addr_1_reg_369 =  (sc_lv<8>) (ap_const_lv64_A7);
}

void KeccakWidth1600_Spon_3::thread_instance_state_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        instance_state_address0 =  (sc_lv<8>) (zext_ln394_fu_322_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        instance_state_address0 = instance_state_addr_1_reg_369.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        instance_state_address0 =  (sc_lv<8>) (ap_const_lv64_A7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        instance_state_address0 = instance_state_addr_reg_364.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        instance_state_address0 =  (sc_lv<8>) (zext_ln149_fu_211_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        instance_state_address0 = grp_fromBytesToWords_fu_198_state_address0.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                 esl_seteq<1,1,1>(icmp_ln299_reg_360.read(), ap_const_lv1_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln305_reg_377.read())))) {
        instance_state_address0 = grp_fromWordsToBytes_fu_191_state_address0.read();
    } else {
        instance_state_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void KeccakWidth1600_Spon_3::thread_instance_state_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        instance_state_ce0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        instance_state_ce0 = grp_fromBytesToWords_fu_198_state_ce0.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                 esl_seteq<1,1,1>(icmp_ln299_reg_360.read(), ap_const_lv1_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln305_reg_377.read())))) {
        instance_state_ce0 = grp_fromWordsToBytes_fu_191_state_ce0.read();
    } else {
        instance_state_ce0 = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_3::thread_instance_state_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        instance_state_d0 = xor_ln149_16_fu_223_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        instance_state_d0 = xor_ln149_fu_216_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                 esl_seteq<1,1,1>(icmp_ln299_reg_360.read(), ap_const_lv1_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln305_reg_377.read())))) {
        instance_state_d0 = grp_fromWordsToBytes_fu_191_state_d0.read();
    } else {
        instance_state_d0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void KeccakWidth1600_Spon_3::thread_instance_state_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        instance_state_we0 = ap_const_logic_1;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                 esl_seteq<1,1,1>(icmp_ln299_reg_360.read(), ap_const_lv1_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln305_reg_377.read())))) {
        instance_state_we0 = grp_fromWordsToBytes_fu_191_state_we0.read();
    } else {
        instance_state_we0 = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_3::thread_loop_fu_310_p2() {
    loop_fu_310_p2 = (!loop_0_i1_reg_171.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(loop_0_i1_reg_171.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void KeccakWidth1600_Spon_3::thread_partialBlock_24_fu_277_p2() {
    partialBlock_24_fu_277_p2 = (!ap_const_lv32_A8.is_01() || !offset_assign_reg_158.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_A8) - sc_biguint<32>(offset_assign_reg_158.read()));
}

void KeccakWidth1600_Spon_3::thread_partialBlock_25_fu_283_p3() {
    partialBlock_25_fu_283_p3 = (!icmp_ln323_fu_271_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln323_fu_271_p2.read()[0].to_bool())? partialBlock_24_fu_277_p2.read(): zext_ln322_fu_262_p1.read());
}

void KeccakWidth1600_Spon_3::thread_partialBlock_fu_256_p2() {
    partialBlock_fu_256_p2 = (!ap_const_lv6_20.is_01() || !trunc_ln322_fu_252_p1.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_20) - sc_biguint<6>(trunc_ln322_fu_252_p1.read()));
}

void KeccakWidth1600_Spon_3::thread_stateAsWords_13_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        stateAsWords_13_address0 = grp_fromBytesToWords_fu_198_stateAsWords_address0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln305_reg_377.read()))) {
        stateAsWords_13_address0 = grp_fromWordsToBytes_fu_191_stateAsWords_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        stateAsWords_13_address0 = grp_KeccakP1600OnWords_fu_182_state_address0.read();
    } else {
        stateAsWords_13_address0 =  (sc_lv<5>) ("XXXXX");
    }
}

void KeccakWidth1600_Spon_3::thread_stateAsWords_13_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        stateAsWords_13_ce0 = grp_fromBytesToWords_fu_198_stateAsWords_ce0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln305_reg_377.read()))) {
        stateAsWords_13_ce0 = grp_fromWordsToBytes_fu_191_stateAsWords_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        stateAsWords_13_ce0 = grp_KeccakP1600OnWords_fu_182_state_ce0.read();
    } else {
        stateAsWords_13_ce0 = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_3::thread_stateAsWords_13_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        stateAsWords_13_ce1 = grp_KeccakP1600OnWords_fu_182_state_ce1.read();
    } else {
        stateAsWords_13_ce1 = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_3::thread_stateAsWords_13_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        stateAsWords_13_d0 = grp_fromBytesToWords_fu_198_stateAsWords_d0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        stateAsWords_13_d0 = grp_KeccakP1600OnWords_fu_182_state_d0.read();
    } else {
        stateAsWords_13_d0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void KeccakWidth1600_Spon_3::thread_stateAsWords_13_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        stateAsWords_13_we0 = grp_fromBytesToWords_fu_198_stateAsWords_we0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        stateAsWords_13_we0 = grp_KeccakP1600OnWords_fu_182_state_we0.read();
    } else {
        stateAsWords_13_we0 = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_3::thread_stateAsWords_13_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        stateAsWords_13_we1 = grp_KeccakP1600OnWords_fu_182_state_we1.read();
    } else {
        stateAsWords_13_we1 = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_3::thread_stateAsWords_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        stateAsWords_address0 = grp_fromBytesToWords_fu_198_stateAsWords_address0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(icmp_ln299_reg_360.read(), ap_const_lv1_1))) {
        stateAsWords_address0 = grp_fromWordsToBytes_fu_191_stateAsWords_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        stateAsWords_address0 = grp_KeccakP1600OnWords_fu_182_state_address0.read();
    } else {
        stateAsWords_address0 =  (sc_lv<5>) ("XXXXX");
    }
}

void KeccakWidth1600_Spon_3::thread_stateAsWords_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        stateAsWords_ce0 = grp_fromBytesToWords_fu_198_stateAsWords_ce0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(icmp_ln299_reg_360.read(), ap_const_lv1_1))) {
        stateAsWords_ce0 = grp_fromWordsToBytes_fu_191_stateAsWords_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        stateAsWords_ce0 = grp_KeccakP1600OnWords_fu_182_state_ce0.read();
    } else {
        stateAsWords_ce0 = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_3::thread_stateAsWords_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        stateAsWords_ce1 = grp_KeccakP1600OnWords_fu_182_state_ce1.read();
    } else {
        stateAsWords_ce1 = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_3::thread_stateAsWords_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        stateAsWords_d0 = grp_fromBytesToWords_fu_198_stateAsWords_d0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        stateAsWords_d0 = grp_KeccakP1600OnWords_fu_182_state_d0.read();
    } else {
        stateAsWords_d0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void KeccakWidth1600_Spon_3::thread_stateAsWords_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        stateAsWords_we0 = grp_fromBytesToWords_fu_198_stateAsWords_we0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        stateAsWords_we0 = grp_KeccakP1600OnWords_fu_182_state_we0.read();
    } else {
        stateAsWords_we0 = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_3::thread_stateAsWords_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        stateAsWords_we1 = grp_KeccakP1600OnWords_fu_182_state_we1.read();
    } else {
        stateAsWords_we1 = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_3::thread_tmp_fu_230_p4() {
    tmp_fu_230_p4 = i_0_reg_134.read().range(32, 5);
}

void KeccakWidth1600_Spon_3::thread_trunc_ln304_fu_331_p1() {
    trunc_ln304_fu_331_p1 = curData_0_idx_reg_146.read().range(7-1, 0);
}

void KeccakWidth1600_Spon_3::thread_trunc_ln322_fu_252_p1() {
    trunc_ln322_fu_252_p1 = i_0_reg_134.read().range(6-1, 0);
}

void KeccakWidth1600_Spon_3::thread_trunc_ln394_fu_327_p1() {
    trunc_ln394_fu_327_p1 = loop_0_i1_reg_171.read().range(7-1, 0);
}

void KeccakWidth1600_Spon_3::thread_xor_ln149_16_fu_223_p2() {
    xor_ln149_16_fu_223_p2 = (instance_state_q0.read() ^ ap_const_lv8_80);
}

void KeccakWidth1600_Spon_3::thread_xor_ln149_fu_216_p2() {
    xor_ln149_fu_216_p2 = (instance_state_q0.read() ^ ap_const_lv8_1);
}

void KeccakWidth1600_Spon_3::thread_zext_ln149_fu_211_p1() {
    zext_ln149_fu_211_p1 = esl_zext<64,32>(instance_byteIOIndex_read.read());
}

void KeccakWidth1600_Spon_3::thread_zext_ln322_fu_262_p1() {
    zext_ln322_fu_262_p1 = esl_zext<32,6>(partialBlock_reg_381.read());
}

void KeccakWidth1600_Spon_3::thread_zext_ln325_3_fu_295_p1() {
    zext_ln325_3_fu_295_p1 = esl_zext<33,32>(partialBlock_25_fu_283_p3.read());
}

void KeccakWidth1600_Spon_3::thread_zext_ln325_fu_291_p1() {
    zext_ln325_fu_291_p1 = esl_zext<64,32>(partialBlock_25_fu_283_p3.read());
}

void KeccakWidth1600_Spon_3::thread_zext_ln394_2_fu_351_p1() {
    zext_ln394_2_fu_351_p1 = esl_zext<64,7>(add_ln394_2_reg_415.read());
}

void KeccakWidth1600_Spon_3::thread_zext_ln394_fu_322_p1() {
    zext_ln394_fu_322_p1 = esl_zext<64,32>(add_ln394_fu_316_p2.read());
}

void KeccakWidth1600_Spon_3::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(icmp_ln299_fu_205_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(icmp_ln299_fu_205_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(grp_fromBytesToWords_fu_198_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(grp_KeccakP1600OnWords_fu_182_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_block_state10_on_subcall_done.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(icmp_ln304_fu_240_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln304_fu_240_p2.read()) && esl_seteq<1,1,1>(icmp_ln305_fu_246_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state16;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(grp_fromBytesToWords_fu_198_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(grp_KeccakP1600OnWords_fu_182_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(ap_block_state16_on_subcall_done.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state17;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln393_fu_305_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state19;
            }
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<19>) ("XXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

